import { GridMetaDataType } from "@acuteinfo/common-base";
export const TRN002_TableMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Today's Transactions",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideHeader: false,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "30vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "Voucher No.",
      sequence: 1,
      componentType: "default",
      width: 100,
    },
    {
      accessor: "ACCT_CD_NEW",
      columnName: "AccountNo",
      sequence: 2,
      componentType: "default",
      width: 180,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountHolder",
      sequence: 3,
      componentType: "default",
      width: 200,
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      sequence: 4,
      componentType: "default",
      width: 20,
    },
    {
      accessor: "SCROLL1",
      columnName: "Scroll/Token",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      accessor: "SDC",
      columnName: "SDC",
      sequence: 6,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 7,
      componentType: "default",
      width: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "EnteredDate",
      sequence: 8,
      width: 70,
      componentType: "date",
      isVisible: true,
    },
    {
      accessor: "TIME",
      columnName: "Time",
      sequence: 9,
      width: 30,
      componentType: "default",
    },
    {
      accessor: "AMOUNT",
      columnName: "Amount",
      sequence: 10,
      componentType: "currency",
      width: 120,
      alignment: "right",
      isDisplayTotal: true,
    },

    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 11,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "Entered Branch",
      sequence: 12,
      componentType: "default",
      width: 80,
    },
  ],
};
