import { AuthSDK } from "registry/fns/auth";
import { DefaultErrorObject } from "components/utils";

// import { DefaultErrorObject } from "components/utils";

export const BranchSelectionGridData = async () => {
  // const { data, status, message, messageDetails } =
  //   await AuthSDK.internalFetcher("GETPUSHNOTIFTEMPLATEGRID", {
  //     CONFIRMED: "ALL",/////////////
  //   });
  // if (status === "0") {
  //   return data;
  // } else {
  //   throw DefaultErrorObject(message, messageDetails);
  // }
  return [
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "B",
      EOD_RUNNING_STATUS: "H",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0002 MAIN BRANCH",
      DISPLAY_NAME: "MAIN BRANCH",
      STATUS: "Open",
      BRANCH_CD: "0002",
      END_DATETIME: "",
      BRANCH_NM: "MAIN BRANCH",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0003 RAIYA ROAD ",
      DISPLAY_NAME: "RAIYA ROAD ",
      STATUS: "Open",
      BRANCH_CD: "0003",
      END_DATETIME: "2023-02-08 18:58:18.0",
      BRANCH_NM: "RAIYA ROAD ",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0005 VANIAWADI",
      DISPLAY_NAME: "VANIAWADI",
      STATUS: "Open",
      BRANCH_CD: "0005",
      END_DATETIME: "2023-02-08 18:51:46.0",
      BRANCH_NM: "VANIAWADI",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0006 MAVDI ROAD",
      DISPLAY_NAME: "MAVDI ROAD",
      STATUS: "Open",
      BRANCH_CD: "0006",
      END_DATETIME: "2023-02-08 19:27:55.0",
      BRANCH_NM: "MAVDI ROAD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0007 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0007",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0007 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0008",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0009 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0009",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0007 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0010",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0007 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0011",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0007 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0012",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0007 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0013",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
    {
      BASE_COMP_CD: "473 ",
      COMP_CD: "473 ",
      DAYEND_STATUS: "E",
      EOD_RUNNING_STATUS: "N",
      BASE_BRANCH_CD: "0002",
      COMP_BASE_BRANCH_CD: "0002",
      DISP_NM: "0007 BEDI YARD",
      DISPLAY_NAME: "BEDI YARD",
      STATUS: "Closed",
      BRANCH_CD: "0014",
      END_DATETIME: "2023-02-08 18:18:16.0",
      BRANCH_NM: "BEDI YARD",
      COMP_NM: "THE RAJKOT COMMERCIAL CO-OPERATIVE BANK LTD",
      SERVICE_TYPE: "B",
      _rowColor: "rgba(255, 79, 121, 0.1)",
      BEGIN_DATETIME: "2023-02-08 00:01:53.0",
    },
  ];
};
