import { GridMetaDataType } from "components/dataTableStatic";
export const BranchSelectionGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "BRANCH_CD",

    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },

    allowColumnReordering: false,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: false,
    containerHeight: {
      min: "60vh",
      max: "60vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hideFooter: true,
  },
  // filters: [
  //   {
  //     accessor: "label",
  //     columnName: "Screen Name",
  //     filterComponentType: "valueFilter",
  //     gridProps: {
  //       xs: 12,
  //       md: 12,
  //       sm: 12,
  //     },
  //   },
  // ],
  columns: [
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BRANCH_NM",
      columnName: "Branch Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 260,
      minWidth: 260,
      maxWidth: 400,
    },
    {
      accessor: "STATUS",
      columnName: "Status",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BEGIN_DATETIME",
      columnName: "Begin Time",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 202,
      minWidth: 120,
      maxWidth: 220,
    },
    {
      accessor: "END_DATETIME",
      columnName: "End Time",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 202,
      minWidth: 120,
      maxWidth: 220,
    },
    {
      accessor: "DAYEND_STATUS",
      columnName: "Dayend Status",
      sequence: 6,
      componentType: "default",
      isVisible: false,
    },
    {
      accessor: "EOD_RUNNING_STATUS",
      columnName: "EOD Running Status",
      sequence: 6,
      componentType: "default",
      isVisible: false,
    },
    {
      accessor: "BASE_COMP_CD",
      columnName: "EOD Running Status",
      sequence: 6,
      componentType: "default",
      isVisible: false,
    },
    {
      accessor: "BASE_BRANCH_CD",
      columnName: "EOD Running Status",
      sequence: 6,
      componentType: "default",
      isVisible: false,
    },
    {
      accessor: "COMP_CD",
      columnName: "EOD Running Status",
      sequence: 6,
      componentType: "default",
      isVisible: false,
    },
    {
      accessor: "COMP_NM",
      columnName: "EOD Running Status",
      sequence: 6,
      componentType: "default",
      isVisible: false,
    },
  ],
};
