import { GeneralAPI } from "registry/fns/functions";
// import { getReportData } from "../detailStatic";

export const stockEntryMetadata = {
  masterForm: {
    form: {
      name: "chequeBookForm",
      label: "Stock Entry",
      resetFieldOnUnmount: false,
      validationRun: "onBlur",
      submitAction: "home",
      formStyle: {
        background: "white",
        height: "calc(100vh - 390px)",
        overflowY: "auto",
        overflowX: "hidden",
      },
      render: {
        ordering: "sequence",
        renderType: "simple",
        gridConfig: {
          item: {
            xs: 12,
            sm: 4,
            md: 4,
          },
          container: {
            direction: "row",
            spacing: 1,
            height: "35vh",
          },
        },
      },
      componentProps: {
        textField: {
          fullWidth: true,
        },
        select: {
          fullWidth: true,
        },
        datePicker: {
          fullWidth: true,
        },
        numberFormat: {
          fullWidth: true,
        },
        inputMask: {
          fullWidth: true,
        },
        datetimePicker: {
          fullWidth: true,
        },
      },
      apiKey: {
        BRANCH_CD: "BRANCH_CD",
        ACCT_TYPE: "ACCT_TYPE",
        ACCT_CD: "ACCT_CD",
      },
    },
    fields: [
      // {
      //   render: {
      //     componentType: "_accountNumber",
      //   },
      //   name: "dfk",
      // },
      {
        render: {
          componentType: "autocomplete",
        },
        name: "BRANCH_CD",
        label: "Branch",
        placeholder: "Branch Code",
        type: "text",
        required: true,
        // maxLength: 16,
        options: GeneralAPI.getBranchCodeList,
        _optionsKey: "getBranchCodeList",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
        schemaValidation: {
          type: "string",
          rules: [{ name: "required", params: ["Branch Code is required."] }],
        },
      },
      {
        render: {
          componentType: "autocomplete",
        },
        name: "ACCT_TYPE",
        label: "AccountType",
        placeholder: "EnterAccountType",
        type: "text",
        required: true,
        options: GeneralAPI.getAccountTypeList,
        _optionsKey: "getAccountTypeList",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
        schemaValidation: {
          type: "string",
          rules: [{ name: "required", params: ["Account Type is required."] }],
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "ACCT_CD",
        label: "ACNo",
        placeholder: "EnterAcNo",
        type: "text",
        fullWidth: true,
        required: true,
        maxLength: 20,
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "FCRss",
        label: "Account Name",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "FCss",
        label: "Security",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "FFFR",
        label: "Script",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "FCR",
        label: "A/C Limit Amount",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "datePicker",
        },
        name: "FRS",
        label: "Statement Date",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "datePicker",
        },
        name: "FRSAA",
        label: "Statement Valid till Date",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "FRS",
        label: "No.of Share(s)",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },

      {
        render: {
          componentType: "textField",
        },
        name: "FRSASD",
        label: "Stock Value",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "FRSDC",
        label: "Net Value",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "FRS",
        label: "Margin %",
        placeholder: "",
        type: "text",
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
    ],
  },
  detailsGrid: {
    gridConfig: {
      dense: true,
      gridLabel: "Stock Entry",
      rowIdColumn: "TRAN_CD",
      defaultColumnConfig: {
        width: 150,
        maxWidth: 250,
        minWidth: 100,
      },
      allowColumnReordering: true,
      disableSorting: false,
      disableGroupBy: true,
      enablePagination: true,
      hideFooter: true,
      pageSizes: [10, 20, 30],
      defaultPageSize: 10,
      containerHeight: {
        min: "25vh",
        max: "25vh",
      },
      allowFilter: false,
      allowColumnHiding: false,
      allowRowSelection: false,
    },
    filters: [],
    columns: [
      {
        accessor: "ID",
        columnName: "Sr.No.",
        sequence: 1,
        alignment: "center",
        componentType: "default",
        width: 70,
        minWidth: 70,
        maxWidth: 200,
        isAutoSequence: true,
      },
      {
        accessor: "TTASQ",
        columnName: "St. Date",
        sequence: 3,
        alignment: "center",
        componentType: "date",
        dateFormat: "dd/MM/yyyy",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },
      {
        accessor: "TTASASDQ",
        columnName: "Stock Till Date",
        sequence: 3,
        alignment: "center",
        componentType: "date",
        dateFormat: "dd/MM/yyyy",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },
      {
        accessor: "ENTRY_DT",
        columnName: "Stock Description",
        sequence: 2,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },
      {
        accessor: "ENTRY_DaT",
        columnName: "Margin",
        sequence: 2,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },
      {
        accessor: "TT",
        columnName: "Stock Value",
        sequence: 3,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },
      {
        accessor: "EXPIRY_DT",
        columnName: "Drawing Power",
        sequence: 3,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },

      {
        accessor: "PENAL_RATE",
        columnName: "Entered Date",
        sequence: 6,
        alignment: "center",
        componentType: "date",
        width: 120,
        minWidth: 100,
        maxWidth: 400,
      },
      {
        accessor: "SECURITY_VALUE",
        columnName: "Received Date",
        sequence: 6,
        alignment: "center",
        componentType: "date",
        width: 120,
        minWidth: 100,
        maxWidth: 400,
      },
    ],
  },
};
