import { GeneralAPI } from "registry/fns/functions";

export const stopPaymentEntryMetadata = {
  masterForm: {
    form: {
      name: "chequeBookForm",
      label: "Stop Payment Entry",
      resetFieldOnUnmount: false,
      validationRun: "onChange",
      submitAction: "home",
      hideHeader: true,
      formStyle: {
        background: "white",
        height: "calc(100vh - 390px)",
        overflowY: "auto",
        overflowX: "hidden",
      },
      render: {
        ordering: "sequence",
        renderType: "simple",
        gridConfig: {
          item: {
            xs: 12,
            sm: 4,
            md: 4,
          },
          container: {
            direction: "row",
            spacing: 1,
            height: "35vh",
          },
        },
      },
      componentProps: {
        textField: {
          fullWidth: true,
        },
        select: {
          fullWidth: true,
        },
        datePicker: {
          fullWidth: true,
        },
        numberFormat: {
          fullWidth: true,
        },
        inputMask: {
          fullWidth: true,
        },
        datetimePicker: {
          fullWidth: true,
        },
      },
      apiKey: {
        BRANCH_CD: "BRANCH_CD",
        ACCT_TYPE: "ACCT_TYPE",
        ACCT_CD: "ACCT_CD",
      },
    },
    fields: [
      // {
      //   render: {
      //     componentType: "_accountNumber",
      //   },
      //   name: "dfk",
      // },
      {
        render: {
          componentType: "autocomplete",
        },
        name: "BRANCH_CD",
        label: "Branch",
        placeholder: "Branch Code",
        type: "text",
        required: true,
        // maxLength: 16,
        options: GeneralAPI.getBranchCodeList,
        _optionsKey: "getBranchCodeList",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
        schemaValidation: {
          type: "string",
          rules: [{ name: "required", params: ["Branch Code is required."] }],
        },
      },
      {
        render: {
          componentType: "autocomplete",
        },
        name: "ACCT_TYPE",
        label: "AccountType",
        placeholder: "EnterAccountType",
        type: "text",
        required: true,
        options: GeneralAPI.getAccountTypeList,
        _optionsKey: "getAccountTypeList",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
        schemaValidation: {
          type: "string",
          rules: [{ name: "required", params: ["Account Type is required."] }],
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "ACCT_CD",
        label: "ACNo",
        placeholder: "EnterAcNo",
        type: "text",
        fullWidth: true,
        required: true,
        maxLength: 20,
        schemaValidation: {
          type: "string",
          rules: [{ name: "required", params: ["Account No. is required."] }],
        },
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },

      {
        render: {
          componentType: "datePicker",
        },
        name: "EXPIRY_DT",
        // sequence: 9,
        label: "Intimate Date",
        placeholder: "",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },

      {
        render: {
          componentType: "textField",
        },
        name: "REMARKS",
        // sequence: 10,
        label: "Cheque From",
        // placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LIMIT_AMOUN",
        // sequence: 10,
        label: "Cheque To",
        // placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },

      {
        render: {
          componentType: "datePicker",
        },
        name: "EXPIY_DT",
        // sequence: 9,
        label: "Cheque Date",
        placeholder: "",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LIMITMOUNT",
        // sequence: 10,
        label: "Cheque Amount",
        // placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LIMIT_AMOUT",
        // sequence: 10,
        label: "Remarks",
        placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LIMIT_AMOUNTSD",
        // sequence: 10,
        label: "Reason",
        placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LIMOUNTSD",
        // sequence: 10,
        label: "Infavour",
        placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LIMOUNTSSDFGD",
        // sequence: 10,
        label: "Charge Amount",
        placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LIMOUNSWERTSSDFGD",
        // sequence: 10,
        label: "GST",
        placeholder: "Enter remark.",
        GridProps: {
          xs: 12,
          md: 3,
          sm: 3,
          lg: 3,
          xl: 3,
        },
      },
    ],
  },
  detailsGrid: {
    gridConfig: {
      dense: true,
      gridLabel: "Stop Payment Entry",
      rowIdColumn: "TRAN_CD",
      defaultColumnConfig: {
        width: 150,
        maxWidth: 250,
        minWidth: 100,
      },
      allowColumnReordering: true,
      disableSorting: false,
      disableGroupBy: true,
      enablePagination: true,
      hideFooter: true,
      pageSizes: [10, 20, 30],
      defaultPageSize: 10,
      containerHeight: {
        min: "31vh",
        max: "31vh",
      },
      allowFilter: false,
      allowColumnHiding: false,
      allowRowSelection: false,
    },
    filters: [],
    columns: [
      {
        accessor: "ID",
        columnName: "Sr.No.",
        sequence: 1,
        alignment: "center",
        componentType: "default",
        width: 70,
        minWidth: 70,
        maxWidth: 200,
        isAutoSequence: true,
      },
      {
        accessor: "ENTRY_DT",
        columnName: "Intimate Date",
        sequence: 2,
        alignment: "center",
        componentType: "date",
        dateFormat: "dd/MM/yyyy",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },
      {
        accessor: "INT_RE",
        columnName: "Cheque From",
        sequence: 4,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
        isVisible: true,
      },
      {
        accessor: "INT_DFGRATE",
        columnName: "Cheque To",
        sequence: 4,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
        isVisible: true,
      },
      {
        accessor: "TT",
        columnName: "Cheque Date",
        sequence: 3,
        alignment: "center",
        componentType: "date",
        dateFormat: "dd/MM/yyyy",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
      },

      {
        accessor: "INT_RAATE",
        columnName: "Cheque Amount",
        sequence: 4,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
        isVisible: true,
      },
      {
        accessor: "INT_RAATESD",
        columnName: "Remarks",
        sequence: 4,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
        isVisible: true,
      },
      {
        accessor: "INT_RAAZTESD",
        columnName: "Flag",
        sequence: 4,
        alignment: "center",
        componentType: "default",
        width: 120,
        minWidth: 100,
        maxWidth: 200,
        isVisible: true,
      },
    ],
  },
};
