import { GridMetaDataType } from "components/dataTableStatic";

export const lienConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "LienConfirmation",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "73vh",
      max: "73vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    searchPlaceholder: "Records of Lien Confirmation",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "FULL_ACCT_NO",
      columnName: "AccountNumber",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 190,
      maxWidth: 290,
    },
    {
      accessor: "LIEN_CD",
      columnName: "LienCode",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 140,
    },

    {
      accessor: "PARENT_CD_NM",
      columnName: "ParentCodeName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 132,
      minWidth: 70,
      maxWidth: 250,
    },
    {
      accessor: "LIEN_STATUS_DISPLAY",
      columnName: "LienStatus",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 112,
      minWidth: 70,
      maxWidth: 150,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 70,
      maxWidth: 250,
    },

    {
      accessor: "EFECTIVE_DT",
      columnName: "EffectiveDate",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 136,
      minWidth: 70,
      maxWidth: 150,
    },

    {
      accessor: "ENTERED_DATE",
      columnName: "EnteredDate",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 141,
      minWidth: 70,
      maxWidth: 150,
    },
    {
      accessor: "LIEN_REASON_NM",
      columnName: "LienReason",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
