import { GridMetaDataType } from "components/dataTableStatic";

export const lienConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Lien Confirmation",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [12, 20, 30],
    defaultPageSize: 12,
    containerHeight: {
      min: "66vh",
      max: "66vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    searchPlaceholder: "Records of Lien Confirmation",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "FULL_ACCT_NO",
      columnName: "Account No.",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account Holder Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 190,
      maxWidth: 290,
    },
    {
      accessor: "LIEN_CD",
      columnName: "Lien Code",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 140,
    },

    {
      accessor: "PARENT_CD_NM",
      columnName: "Parent Code/Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 70,
      maxWidth: 250,
    },
    {
      accessor: "LIEN_STATUS",
      columnName: "Lien Status",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 107,
      minWidth: 70,
      maxWidth: 150,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 70,
      maxWidth: 250,
    },

    {
      accessor: "EFECTIVE_DT",
      columnName: "Effective Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 70,
      maxWidth: 150,
    },

    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 115,
      minWidth: 70,
      maxWidth: 150,
    },

    {
      accessor: "LIEN_REASON_NM",
      columnName: "Lien Reason ",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
