import { GridMetaDataType } from "components/dataTableStatic";

export const stockConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Stock Confirmation",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [12, 20, 30],
    defaultPageSize: 12,
    containerHeight: {
      min: "66vh",
      max: "66vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    searchPlaceholder: "Records of Stock Confirmation",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "TRAN_DT",
      columnName: "Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 90,
      minWidth: 70,
      maxWidth: 120,
    },

    {
      accessor: "FULL_ACCT_NO",
      columnName: "Account No.",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account Holder Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 190,
      maxWidth: 290,
    },

    {
      accessor: "ASON_DT",
      columnName: "Stock Ason Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 136,
      minWidth: 70,
      maxWidth: 150,
    },

    {
      accessor: "STOCK_DESC",
      columnName: "Stock Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 290,
    },

    {
      accessor: "STOCK_VALUE",
      columnName: "Stock Value",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 93,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      accessor: "MARGIN",
      columnName: "Margin",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 62,
      minWidth: 50,
      maxWidth: 100,
    },

    {
      accessor: "DRAWING_POWER",
      columnName: "Drawing Power",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 107,
      minWidth: 90,
      maxWidth: 160,
    },

    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Last Entered By",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 132,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "TRAN_BAL",
      columnName: "Balance",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 103,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 80,
      maxWidth: 250,
    },

    {
      accessor: "VERIFIED_BY",
      columnName: "Verified By",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
