import { GridMetaDataType } from "components/dataTableStatic";

export const stopPayConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Stop Payment Confirmation",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [12, 20, 30],
    defaultPageSize: 12,
    containerHeight: {
      min: "66vh",
      max: "66vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    searchPlaceholder: "Records of Stop Payment Confirmation",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "TRAN_DT",
      columnName: "Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 90,
      minWidth: 70,
      maxWidth: 120,
    },

    {
      accessor: "FULL_ACCT_NO",
      columnName: "Account No.",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account Holder Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 190,
      maxWidth: 290,
    },
    {
      accessor: "CHEQUE_FROM_TO",
      columnName: "Cheque From - To",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 142,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "CHEQUE_DT",
      columnName: "Cheque Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 115,
      minWidth: 70,
      maxWidth: 150,
    },

    {
      accessor: "CHEQUE_AMOUNT",
      columnName: "Cheque Amount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Last Entered By",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 132,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "TRAN_BAL",
      columnName: "Balance",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 103,
      minWidth: 80,
      maxWidth: 150,
    },

    {
      accessor: "VERIFIED_BY",
      columnName: "Verified By",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
