import { GridMetaDataType } from "components/dataTableStatic";
export const TodayTransGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Today Transaction Details",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 120,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Time",
      accessor: "time",
      sequence: 2,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Chq No.",
      accessor: "CHEQUE_NO",
      sequence: 3,
      componentType: "default",
      width: 100,
      alignment: "right",
    },
    {
      columnName: "Trx",
      accessor: "TYPE_CD",
      sequence: 4,
      componentType: "default",
      width: 70,
      maxWidth: 100,
      minWidth: 70,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Credit",
      accessor: "CREDIT",
      sequence: 6,
      componentType: "currency",
      width: 120,
      color: "green",
      alignment: "right",
    },

    {
      columnName: "Debit",
      accessor: "DEBIT",
      sequence: 7,
      componentType: "currency",
      width: 120,
      color: "red",
      alignment: "right",
    },
    {
      columnName: "Voucher No",
      accessor: "TRAN_CD",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Status",
      accessor: "STATUS",
      sequence: 9,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Br",
      accessor: "ENTERED_BRANCH_CD",
      sequence: 10,
      componentType: "default",
      width: 70,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Scroll",
      accessor: "SCROLL1",
      sequence: 11,
      componentType: "default",
      width: 100,
      maxWidth: 100,
      minWidth: 50,
      alignment: "right",
    },
    {
      columnName: "SDC",
      accessor: "SDC",
      sequence: 12,
      componentType: "default",
      width: 100,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Maker",
      accessor: "MAKER",
      sequence: 13,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Checker",
      accessor: "CHECKER",
      sequence: 14,
      componentType: "default",
      width: 120,
    },

    {
      columnName: "Date",
      accessor: "TRAN_DT",
      sequence: 15,
      width: 120,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
    },
  ],
};

//////////////////////////////////////////////////////////////////

export const AccountDetailsGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Account Details",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 120,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "25.2vh",
      max: "25.2vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      columnName: "Acct.Status",
      accessor: "ACCT_STATUS",
      sequence: 1,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Account No.",
      accessor: "AC_CD",
      sequence: 2,
      componentType: "default",
      width: 220,
    },
    {
      columnName: "Account Name/Person Name",
      accessor: "ACCT_NM",
      sequence: 3,
      componentType: "default",
      width: 300,
    },
    {
      columnName: "Opening Date",
      accessor: "OP_DATE",
      sequence: 4,
      componentType: "date",
      width: 220,
    },
    {
      columnName: "Status",
      accessor: "ORG_STATUS",
      sequence: 5,
      componentType: "default",
      width: 130,
    },
    {
      columnName: "Close Date",
      accessor: "CLOSE_DT",
      sequence: 6,
      componentType: "date",
      width: 220,
    },
  ],
};
