import { GridMetaDataType } from "components/dataTableStatic";
export const TodayTransGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Today Transaction Details",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 120,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Time",
      accessor: "time",
      sequence: 2,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Chq No.",
      accessor: "CHEQUE_NO",
      sequence: 3,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Trx",
      accessor: "TYPE_CD",
      sequence: 4,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Credit",
      accessor: "CREDIT",
      sequence: 6,
      componentType: "currency",
      width: 120,
      color: "green",
    },

    {
      columnName: "Debit",
      accessor: "DEBIT",
      sequence: 7,
      componentType: "currency",
      width: 120,
      color: "red",
    },
    {
      columnName: "Voucher No",
      accessor: "TRAN_CD",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Status",
      accessor: "Status",
      sequence: 9,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Br",
      accessor: "Br",
      sequence: 10,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Scroll",
      accessor: "SCROLL1",
      sequence: 11,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "SDC",
      accessor: "SDC",
      sequence: 12,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Maker",
      accessor: "MAKER",
      sequence: 13,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Checker",
      accessor: "CHECKER",
      sequence: 14,
      componentType: "default",
      width: 120,
    },

    {
      columnName: "Date",
      accessor: "TRAN_DT",
      sequence: 15,
      width: 120,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
    },
  ],
};
