import { GridMetaDataType } from "components/dataTableStatic";
export const BillerFieldOptionsGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Field Options",
    rowIdColumn: "LINE_ID",
    defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
    allowColumnReordering: true,
    disableGroupBy: true,
    disableSorting: true,
    hideHeader: true,
    containerHeight: { min: "50vh", max: "60vh" },
    allowRowSelection: false,
  },
  columns: [
    {
      columnName: "Serial No",
      componentType: "default",
      accessor: "LINE_ID",
      sequence: 0,
      alignment: "left",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      columnName: "Options Name",
      componentType: "default",
      accessor: "OPTIONS_NAME",
      sequence: 1,
      alignment: "left",
      width: 300,
      minWidth: 200,
      maxWidth: 500,
    },
    {
      columnName: "Options Value",
      componentType: "default",
      accessor: "OPTIONS_VALUE",
      sequence: 2,
      alignment: "left",
      width: 300,
      minWidth: 200,
      maxWidth: 500,
    },
  ],
};
