import { GridMetaDataType } from "components/dataTableStatic";
export const AccountDeletionReqGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Account Deletion Request",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "Ref.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "PRIMARY_ACCT_NO",
      columnName: "Primary Account",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "PRIMARY_APP_SOURCE",
      columnName: "Primary Source",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "PRIMARY_CBNUMBER",
      columnName: "Primary CB No.",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "DELETION_REASON",
      columnName: "Deletion Reason",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "REQ_DT",
      columnName: "Request Date",
      sequence: 13,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 140,
      minWidth: 130,
      maxWidth: 170,
    },
  ],
};
