import { GridMetaDataType } from "components/dataTableStatic";
export const CategoryMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: false,
    gridLabel: "Category Master (MST/050)",
    rowIdColumn: "CATEG_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 30, 50],
    defaultPageSize: 10,
    containerHeight: {
      min: "77vh",
      max: "77vh",
    },
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 40,
      maxWidth: 70,
      isAutoSequence: true,
    },
    {
      accessor: "CATEG_CD",
      columnName: "Code",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 40,
      maxWidth: 70,
    },
    {
      accessor: "CATEG_NM",
      columnName: "Category Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
    {
      accessor: "CONSTITUTION_TYPE_DESC",
      columnName: "Type Of Constitution",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 170,
      maxWidth: 200,
    },
    {
      accessor: "TDS_LIMIT",
      columnName: "TDS Limit",
      sequence: 5,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "TDS_RATE",
      columnName: "TDS Payable Rate",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "TDS_BRANCH_CD",
      columnName: "TDS Payable Branch",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "TDS_ACCT_TYPE",
      columnName: "TDS Payable Type",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "TDS_ACCT_CD",
      columnName: "TDS Payable A/c No.",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "TDS_ACCT_NM",
      columnName: "TDS Payable Account Name",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 170,
      maxWidth: 190,
    },
    {
      accessor: "TDS_SURCHARGE",
      columnName: "Surcharge Rate",
      sequence: 11,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "TDS_SUR_ACCT_TYPE",
      columnName: "Surcharge Type",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "TDS_SUR_ACCT_CD",
      columnName: "Surcharge A/c No.",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "TDS_REC_BRANCH_CD",
      columnName: "TDS Receivable Branch",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 150,
      maxWidth: 170,
    },
    {
      accessor: "TDS_REC_ACCT_TYPE",
      columnName: "TDS Receivable Type",
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "TDS_REC_ACCT_CD",
      columnName: "TDS Receivable A/c No.",
      sequence: 16,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 150,
      maxWidth: 170,
    },
    {
      accessor: "TDS_REC_ACCT_NM",
      columnName: "TDS Receivable Account Name",
      sequence: 17,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 190,
      maxWidth: 210,
    },
    {
      accessor: "DROPDOWN_DISP",
      columnName: "Minor/Major",
      sequence: 18,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 120,
    },
  ],
};
