import { GridMetaDataType } from "components/dataTableStatic";
export const LienDetailGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Lien Detail",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },

    {
      columnName: "Lien No.",
      accessor: "LIEN_CD",
      sequence: 2,
      componentType: "default",
      width: 80,
    },

    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 3,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Effective Date",
      accessor: "EFECTIVE_DT",
      sequence: 4,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 80,
    },
    {
      columnName: "Removal Date",
      accessor: "REMOVAL_DT",
      sequence: 5,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 80,
    },
    {
      columnName: "Lien Amount",
      accessor: "LIEN_AMOUNT",
      sequence: 6,
      componentType: "currency",
      width: 80,
    },
    {
      columnName: "Status",
      accessor: "LIEN_STATUS",
      sequence: 7,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Confirmed",
      accessor: "CONFIRMED",
      sequence: 8,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Reason",
      accessor: "REASON_NM",
      sequence: 9,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Entered By",
      accessor: "ENTERED_BY",
      sequence: 10,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Verified By",
      accessor: "VERIFIED_BY",
      sequence: 11,
      componentType: "default",
      width: 80,
    },
  ],
};
