import { GridMetaDataType } from "components/dataTableStatic";

export const FdschemeMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "FD Scheme Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "FDR_ACCT_TYPE",
      columnName: "FD Account type",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "SCHEME_CODE",
      columnName: "Scheme Code",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "MATURITY_INST",
      columnName: "Maturity Instruction",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      isVisible: false,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "NATURE_OF_ACCOUNT",
      columnName: "Nature of Account",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 300,
    },
    {
      accessor: "CURRENCY",
      columnName: "CCY.",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 50,
      maxWidth: 100,
      showTooltip: true,
    },
    {
      accessor: "FDR_ACCT_TYPE",
      columnName: "Account type",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "TENOR_TYPE_FINACLE",
      columnName: "Tenure Type Finacle",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "TENOR",
      columnName: "Tenure",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "TENOR_TYPE_RATE",
      columnName: "Tenure Type Rate",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "RENEWAL",
      columnName: "Renewal",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "MATURITY_INST",
      columnName: "Maturity Inst.",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "SCHEME_CODE",
      columnName: "Scheme Code",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "SCHEME_DESC",
      columnName: "Scheme Description",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "FD_MOD_AMT",
      columnName: "TD Mod Amount",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
