import { GridMetaDataType } from "@acuteinfo/common-base";
import { getHoldChargeDropDown } from "./api";
export const HoldChargeGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Hold Charge",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Dr.Type",
      accessor: "ACCT_TYPE",
      sequence: 2,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Dr.A/C No.",
      accessor: "ACCT_CD",
      sequence: 3,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Cr.Br.",
      accessor: "TO_BRANCH_CD",
      sequence: 4,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Cr. Type",
      accessor: "TO_ACCT_TYPE",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Cr. A/C No.",
      accessor: "TO_ACCT_CD",
      sequence: 6,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Hold Date",
      accessor: "ENTERED_DATE",
      sequence: 7,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 100,
    },
    {
      columnName: "Trx",
      accessor: "TYPE_CD",
      sequence: 8,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 9,
      componentType: "default",
      width: 200,
    },
    {
      columnName: "Amount",
      accessor: "AMOUNT",
      sequence: 10,
      componentType: "currency",
      width: 100,
      alignment: "right",
    },
    {
      columnName: "Paid/Wave",
      accessor: "PAID",
      sequence: 11,
      componentType: "editableSelect",
      options: getHoldChargeDropDown,
      _optionsKey: "HoldChargeDropDown",
      width: 100,
    },
    {
      columnName: "Ent.Br.",
      accessor: "ENTERED_BRANCH_CD",
      sequence: 12,
      componentType: "default",
      width: 120,
    },
  ],
};
