import { GridMetaDataType } from "@acuteinfo/common-base";
export const IMPSGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "IMPS",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "RegDate",
      accessor: "REG_DT",
      sequence: 2,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 100,
    },
    {
      columnName: "IFTDailyLimit",
      accessor: "PERDAY_IFT_LIMIT",
      sequence: 3,
      componentType: "currency",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "RTGSDayLimit",
      accessor: "PERDAY_RTGS_LIMIT",
      sequence: 4,
      componentType: "currency",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "NEFTDayLimit",
      accessor: "PERDAY_NEFT_LIMIT",
      sequence: 5,
      componentType: "currency",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "IMPSP2PDayLimit",
      accessor: "PERDAY_P2P_LIMIT",
      sequence: 6,
      componentType: "currency",
      alignment: "right",
      width: 145,
    },
    {
      columnName: "IMPRP2ADayLimit",
      accessor: "PERDAY_P2A_LIMIT",
      sequence: 7,
      componentType: "currency",
      alignment: "right",
      width: 145,
    },
    {
      columnName: "OWNDayLimit",
      accessor: "PERDAY_OWN_LIMIT",
      sequence: 8,
      componentType: "currency",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "BBPSLimit",
      accessor: "PERDAY_BBPS_LIMIT",
      sequence: 9,
      componentType: "currency",
      alignment: "right",
      width: 100,
    },
  ],
};
