import { GridMetaDataType } from "components/dataTableStatic";
export const IMPSGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "IMPS",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Reg. Date",
      accessor: "REG_DT",
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 100,
    },
    {
      columnName: "IFT/ Daily Limit",
      accessor: "PERDAY_IFT_LIMIT",
      sequence: 3,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "RTGS/Day Limit",
      accessor: "PERDAY_RTGS_LIMIT",
      sequence: 4,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "NEFT/Day Limit",
      accessor: "PERDAY_NEFT_LIMIT",
      sequence: 5,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "IMPS/P2P/",
      accessor: "PERDAY_P2P_LIMIT",
      sequence: 6,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "P2A/Day Limit",
      accessor: "PERDAY_P2A_LIMIT",
      sequence: 7,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "OWN/Day Limit",
      accessor: "PERDAY_OWN_LIMIT",
      sequence: 8,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "BBPS Limit",
      accessor: "9",
      sequence: 9,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
  ],
};
