import { GridMetaDataType } from "@acuteinfo/common-base";
export const APBSGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "APBS",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Register Date",
      accessor: "TRAN_DT",
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Aadhar No.",
      accessor: "3",
      sequence: 3,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "A/C Holder",
      accessor: "4",
      sequence: 4,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Customer ID",
      accessor: "CUSTOMER_ID",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Fresh Registration",
      accessor: "FRESH_REG",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Previous Bank IIN",
      accessor: "PREV_IIN_NO",
      sequence: 7,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Upload in NPCI",
      accessor: "8",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Upload Date",
      accessor: "UPLOAD_DT",
      sequence: 9,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Deactive Date",
      accessor: "DEACTIVE_DT",
      sequence: 10,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Status",
      accessor: "ACTIVE",
      sequence: 11,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Upload File Name",
      accessor: "12",
      sequence: 12,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Remarks",
      accessor: "13",
      sequence: 13,
      componentType: "default",
      width: 120,
    },
  ],
};
