import { GridMetaDataType } from "components/dataTableStatic";
export const ChequeDtlGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Cheque Detail",
    rowIdColumn: "CHEQUE_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Processed Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 102,
      minWidth: 900,
      maxWidth: 130,
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "Cheque No.",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    // {
    //   accessor: "CHEQUE_TO",
    //   columnName: "To Chq. No.",
    //   sequence: 5,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 150,
    //   maxWidth: 200,
    // },

    {
      accessor: "AMOUNT",
      columnName: "Charge",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 80,
      minWidth: 100,
      maxWidth: 130,
    },

    {
      accessor: "FLAG",
      columnName: "Status",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
  ],
};
