import { GridMetaDataType } from "components/dataTableStatic";
export const LimitGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Limit",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Entry Date",
      accessor: "2",
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 100,
    },
    {
      columnName: "Effective Date",
      accessor: "3",
      sequence: 3,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Expiry Date",
      accessor: "4",
      sequence: 4,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Int Rate",
      accessor: "5",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Margin",
      accessor: "6",
      sequence: 6,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Over Rate",
      accessor: "7",
      sequence: 7,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Over Rate",
      accessor: "8",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Security Value",
      accessor: "9",
      sequence: 9,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Limit Amount",
      accessor: "10",
      sequence: 10,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Description",
      accessor: "11",
      sequence: 11,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Resolution Date",
      accessor: "12",
      sequence: 12,
      componentType: "default",
      width: 120,
    },
  ],
};
