import { GridMetaDataType } from "components/dataTableStatic";
export const TodaysTransactionTableGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Todays Transaction",
    rowIdColumn: "DOC_CD",

    defaultColumnConfig: {
      width: 200,
      maxWidth: 300,
      minWidth: 200,
    },

    allowColumnReordering: false,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: false,
    containerHeight: {
      min: "50vh",
      max: "50vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hideFooter: true,
  },
  columns: [
    {
      accessor: "DOC_NM",
      columnName: "Screen Name",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 200,
      maxWidth: 220,
    },
    {
      accessor: "USER_DEFINE_CD",
      columnName: "User Code",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DOC_CD",
      columnName: "System Code",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 180,
      maxWidth: 180,
    },
    {
      accessor: "DOC_DESCRIPTION",
      columnName: "DOC_DESCRIPTION",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 200,
      maxWidth: 220,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "DESCRIPTION",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 120,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "BRANCH_CD",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 120,
    },
  ],
};
