import { GridMetaDataType } from "@acuteinfo/common-base";
export const OwChqGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "OWChqOBCIBC",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 0,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "TranDate",
      accessor: "TRAN_DT",
      sequence: 1,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "chequeNo",
      accessor: "CHEQUE_NO",
      sequence: 2,
      alignment: "right",
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Description",
      accessor: "DESCRIPTION",
      sequence: 3,
      componentType: "default",
      width: 150,
    },
    {
      columnName: "OtherDetails",
      accessor: "STATUS",
      sequence: 4,
      componentType: "default",
      width: 250,
    },
    {
      columnName: "CR_DR",
      accessor: "CR_DR",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Amount",
      accessor: "AMOUNT",
      sequence: 6,
      componentType: "currency",
      alignment: "right",
      width: 120,
    },
    {
      columnName: "Confirm",
      accessor: "CONFIRMED",
      sequence: 7,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Branch",
      accessor: "ENTERED_BRANCH_CD",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
  ],
};
