apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbs-ui-microservice-deployment
  namespace: default
  labels:
    app: cbs-ui-microservice-deployment
spec:
  selector:
    matchLabels:
      app: cbs-ui-microservice-selector
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      name: cbs-ui-microservice-pod
      labels:
        app: cbs-ui-microservice-selector

    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
      - name: cbs-gateway-microservice-container
        image: actdocker123/cbs-micro-service:enfinity-cbsui-V1.0.47
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - touch /opt/iamnotready ; sleep 120
        # resources:
        #   limits:
        #      cpu: 1500m
        #      memory: 4Gi
        #   requests:
        #      cpu: 1000m
        #      memory: 2Gi
        # livenessProbe:
        #    httpGet:
        #       path: /actuator/health/liveness
        #       port: 9103
        #    failureThreshold: 5
        #    periodSeconds: 10
        #    timeoutSeconds: 5
        # startupProbe:
        #    httpGet:
        #       path: /actuator/health
        #       port: 9103
        #    failureThreshold: 5
        #    periodSeconds: 10
        #    initialDelaySeconds: 120
        #    timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "[ ! -f /opt/iamnotready ] || ls -ld /imready &>/dev/null"
          failureThreshold: 2
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        # - name: _JAVA_OPTIONS
        #   value: >-
        #          -Djavax.net.ssl.trustStore=/opt/sslCertificate/keystore.jks
        #          -Djavax.net.ssl.trustStorePassword=citybank123
        - name: POD_IP
          valueFrom:
             fieldRef:
               fieldPath: status.podIP
        - name: TZ
          value: "Asia/Calcutta"
        envFrom:
        - configMapRef:
            name: cbsui-service-ip-config
        volumeMounts: #bind mount with host
        # - mountPath: /opt/API_LOGS/EnfintyCBS-UI ##mount path from container
        #   name: apilogs
        # - name: ssl-config
        #   mountPath: /opt/ssl
        #   readOnly: true
      volumes:
      # - name: apilogs  ##pass the same name as container mount name
      #   hostPath:
      #     path: /opt/API_LOGS/EnfintyCBS-UI ##path from host machine
      # - name: ssl-config
      #   hostPath:
      #     path: /opt/ssl
      imagePullSecrets:
      - name: cbs-enfinity
      terminationGracePeriodSeconds: 150

---
apiVersion: v1
kind: Service
metadata:
  name: cbs-ui-microservice-service
  namespace: default
spec:
    selector:
      app: cbs-ui-microservice-selector
    type: NodePort
    ports:
    - nodePort: 30005 ###external access port
      port : 3000 ###cluster access port
      targetPort: 3000 ###pod/container access port

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cbsui-service-ip-config
data:
  CONFIG_SERVER_IP_PORT: 10.150.17.6:30004
