import { GridMetaDataType } from "@acuteinfo/common-base";
export const DynamicReportAccessRightsGridMData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "DynamicReportAccessRights",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "TITLE",
      columnName: "Title",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 90,
      minWidth: 50,
      maxWidth: 150,
      //isAutoSequence: true,
    },
    {
      accessor: "ACCESS_FLAG",
      columnName: "",
      sequence: 2,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 80,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "USER_NAME",
      columnName: "UserName",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 150,
      maxWidth: 500,
    },
    {
      accessor: "GROUP_NAME",
      columnName: "GroupName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
