const currencySymbol = {
  ALL: "Lek",
  AFN: "؋",
  ARS: "$",
  AWG: "ƒ",
  AUD: "$",
  AZN: "₼",
  BSD: "$",
  BBD: "$",
  BYN: "Br",
  BZD: "BZ$",
  BMD: "$",
  BOB: "$b",
  BAM: "KM",
  BWP: "P",
  BGN: "лв",
  BRL: "R$",
  BND: "$",
  KHR: "៛",
  BDT: "৳",
  CAD: "$",
  KYD: "$",
  CLP: "$",
  CNY: "¥",
  COP: "$",
  CRC: "₡",
  HRK: "kn",
  CUP: "₱",
  CZK: "Kč",
  DKK: "kr",
  DOP: "RD$",
  XCD: "$",
  EGP: "£",
  SVC: "$",
  EUR: "€",
  FKP: "£",
  GIP: "£",
  GTQ: "Q",
  GGP: "£",
  GYD: "$",
  HNL: "L",
  HKD: "$",
  HUF: "Ft",
  INR: "₹", ///////////////////////////////////////////////////////////////////
  IDR: "Rp",
  IRR: "﷼",
  IMP: "£",
  ILS: "₪",
  JMD: "J$",
  JPY: "¥",
  JEP: "£",
  KZT: "лв",
  KPW: "₩",
  KRW: "₩",
  KGS: "лв",
  LAK: "₭",
  LBP: "£",
  LRD: "$",
  MKD: "ден",
  MYR: "RM",
  MUR: "₨",
  MXN: "$",
  MNT: "₮",
  MZN: "MT",
  NAD: "$",
  ANG: "ƒ",
  NZD: "$",
  NIO: "C$",
  NGN: "₦",
  NOK: "kr",
  OMR: "﷼",
  PKR: "₨",
  PAB: "B/.",
  PYG: "Gs",
  PEN: "S/.",
  PHP: "₱",
  PLN: "zł",
  ZAR: "R",
  AED: "د.إ", //  United Arab Emirates Dirham
  CHF: "Fr.", //  Swiss Franc
  GBP: "£", //British Pound Sterling
  RUB: "₽", //Russian Ruble
  SEK: "kr", // Swedish Krona
  TRY: "₺", //Turkish Lira
  USD: "$", //United States Dollar
  VND: "₫", //Vietnamese Dong
  ZWL: "Z$", // Zimbabwean Dollar - obsolete
  BTN: "Nu.",
  BYR: "Br",
  CVE: "€",
  DJF: "Fdj",
  DZD: "دج",
  ERN: "Nfk",
  FJD: "$",
  GEL: "₾",
  GHS: "¢",
  ISK: "kr",
  KWD: "د.ك",
  LKR: "₨",
  LYD: "ل.د",
  MDL: "L",
  MVR: "ރ",
  MWK: "MK",
  NPR: "₨",
  RSD: "din.",
  SAR: "ر.س",
  SCR: "₨",
  SYP: "£",
  TND: "د.ت",
  TTD: "TT$",
  TWD: "NT$",
  UGX: "Ush",
  YER: "﷼",
  ZMW: "K",
  XOF: "CFA",
  XAF: "FCFA",
  TZS: "TSh",
  SZL: "L",
  STN: "Db",
  SSP: "£",
  SOS: "Sh.So.",
  SLL: "Le",
  ETB: "ብር",
};

export default function getCurrencySymbol(currencyCode) {
  return currencySymbol[currencyCode] ?? "₹";
}
