export const atmConfirmMetaData = {
  masterForm: {
    form: {
      name: "atm-Confirm-MetaData",
      label: "",
      resetFieldOnUnmount: false,
      validationRun: "onBlur",
      render: {
        ordering: "auto",
        renderType: "simple",
        gridConfig: {
          item: {
            xs: 12,
            sm: 4,
            md: 4,
          },
          container: {
            direction: "row",
            spacing: 1.5,
          },
        },
      },
    },
    fields: [
      {
        render: {
          componentType: "typography",
        },
        name: "TOTAL",
        label: "",
        shouldExclude: (field) => {
          if (field?.value) {
            return false;
          }
          return true;
        },
        TypographyProps: { variant: "subtitle2" },
        GridProps: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
          xl: 12,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "BRANCH_CD",
        label: "BranchCode",
        fullWidth: true,
        GridProps: {
          xs: 12,
          md: 2,
          sm: 2,
          lg: 2,
          xl: 2,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "ACCT_TYPE",
        label: "AccountType",
        fullWidth: true,
        GridProps: {
          xs: 12,
          md: 2,
          sm: 2,
          lg: 2,
          xl: 2,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "ACCT_CD",
        label: "AccountCode",
        fullWidth: true,
        GridProps: {
          xs: 12,
          md: 2.5,
          sm: 2.5,
          lg: 2.5,
          xl: 2.5,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "ACCT_NM",
        label: "AccountName",
        fullWidth: true,
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "formbutton",
        },
        name: "CARD_PRINT",
        fullWidth: true,
        label: "CardPrinting",
        GridProps: {
          xs: 12,
          sm: 1.5,
          md: 1.5,
          lg: 1.5,
          xl: 1.5,
        },
      },
      {
        render: {
          componentType: "numberFormat",
        },
        fullWidth: true,
        name: "CUSTOMER_ID",
        label: "CustomerId",
        GridProps: {
          xs: 12,
          md: 2,
          sm: 2,
          lg: 2,
          xl: 2,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "ORGINAL_NM",
        fullWidth: true,
        label: "AcctOrignalName",
        GridProps: {
          xs: 12,
          md: 4.5,
          sm: 4.5,
          lg: 4.5,
          xl: 4.5,
        },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "ACCOUNT_NAME",
        fullWidth: true,
        label: "NameOnCard",
        GridProps: {
          xs: 12,
          md: 4,
          sm: 4,
          lg: 4,
          xl: 4,
        },
      },
      {
        render: {
          componentType: "checkbox",
        },
        name: "SMS_ALERT",
        fullWidth: true,
        label: "SMSAlert",
        GridProps: {
          xs: 12,
          sm: 1.5,
          md: 1.5,
          lg: 1.5,
          xl: 1.5,
        },
      },
      {
        render: {
          componentType: "numberFormat",
        },
        name: "MOBILE_NO",
        fullWidth: true,
        label: "MobileNo",
        GridProps: {
          xs: 12,
          md: 2,
          sm: 2,
          lg: 2,
          xl: 2,
        },
      },

      {
        render: {
          componentType: "textField",
        },
        name: "ENTERED_BY",
        fullWidth: true,
        label: "Entered By",
        GridProps: {
          xs: 12,
          md: 2.2,
          sm: 2.2,
          lg: 2.2,
          xl: 2.2,
        },
      },
      {
        render: {
          componentType: "datetimePicker",
        },
        name: "ENTERED_DATE",
        label: "Entered Date",
        format: "dd/MM/yyyy HH:mm:ss",
        fullWidth: true,
        GridProps: { xs: 12, md: 2.3, sm: 2.3, lg: 2.3, xl: 2.3 },
      },
      {
        render: {
          componentType: "textField",
        },
        name: "LAST_MODIFIED_BY",
        fullWidth: true,
        label: "Last Modified By",
        GridProps: {
          xs: 12,
          md: 2,
          sm: 2,
          lg: 2,
          xl: 2,
        },
      },
      {
        render: {
          componentType: "datetimePicker",
        },
        name: "LAST_MODIFIED_DATE",
        label: "Last Modified Date",
        format: "dd/MM/yyyy HH:mm:ss",
        fullWidth: true,
        GridProps: { xs: 12, md: 2, sm: 2, lg: 2, xl: 2 },
      },
    ],
  },
  detailsGrid: {
    gridConfig: {
      dense: true,
      gridLabel: "",
      rowIdColumn: "SR_CD",
      searchPlaceholder: "Accounts",
      defaultColumnConfig: {
        width: 150,
        maxWidth: 250,
        minWidth: 100,
      },
      allowColumnReordering: true,
      disableSorting: false,
      hideHeader: true,
      disableGroupBy: true,
      hiddenFlag: "_hidden",
      enablePagination: false,
      pageSizes: [10, 20, 30],
      defaultPageSize: 10,
      containerHeight: {
        min: "34vh",
        max: "34vh",
      },
      allowFilter: false,
      allowColumnHiding: false,
      allowRowSelection: false,
    },
    // filters: [],
    columns: [
      {
        accessor: "SRNO",
        columnName: "SrNo",
        sequence: 1,
        componentType: "default",
        width: 75,
        minWidth: 50,
        maxWidth: 100,
        isAutoSequence: true,
      },
      {
        accessor: "REQ_DT",
        columnName: "RequestDate",
        sequence: 2,
        componentType: "date",
        dateFormat: "dd/MM/yyyy",
        width: 120,
        maxWidth: 200,
        minWidth: 150,
      },
      {
        accessor: "DISPLAY_STATUS",
        columnName: "CardStatus",
        componentType: "default",
        sequence: 2,
        alignment: "center",
        width: 100,
        minWidth: 200,
        maxWidth: 400,
      },

      {
        accessor: "DISPLAY_CARD_ISSUE_TYPE",
        columnName: "IssueTo",
        sequence: 4,
        componentType: "default",
        width: 120,
        alignment: "center",
      },
      {
        accessor: "CUSTOMER_ID",
        columnName: "CustomerId",
        sequence: 5,
        componentType: "default",
        width: 120,
        alignment: "center",
      },
      {
        accessor: "CUSTOMER_NM",
        columnName: "CustomerName",
        sequence: 6,
        componentType: "default",
        width: 90,
        maxWidth: 100,
        minWidth: 50,
        alignment: "left",
      },
      {
        accessor: "ISSUE_DT",
        columnName: "IssueRejectDate",
        sequence: 7,
        componentType: "date",
        width: 120,
        alignment: "center",
      },

      {
        accessor: "CITIZEN_ID",
        columnName: "CitizenId",
        sequence: 8,
        componentType: "default",
        width: 120,
        alignment: "center",
      },
      {
        accessor: "M_CARD_NO",
        columnName: "CardNo",
        sequence: 9,
        componentType: "default",
        width: 120,
        alignment: "center",
      },
      {
        accessor: "CARD_TYPE",
        columnName: "CardType",
        sequence: 10,
        componentType: "default",
        alignment: "center",
        width: 120,
      },
      {
        accessor: "EXPIRE_DT",
        columnName: "ExpireDate",
        sequence: 12,
        componentType: "date",
        alignment: "center",
        // dateFormat: "dd/MM/yyyy",
        width: 120,
      },
      {
        accessor: "REMARKS",
        columnName: "Remarks",
        sequence: 11,
        componentType: "default",
        alignment: "center",
        width: 120,
      },
      {
        accessor: "DEACTIVE_DT",
        columnName: "DeactiveDate",
        sequence: 12,
        componentType: "date",
        alignment: "center",
        // dateFormat: "dd/MM/yyyy",
        width: 120,
      },
    ],
  },
};
