import { GridMetaDataType } from "components/dataTableStatic";
export const BillerConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Dynamic Biller Confirmation",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "70vh",
      max: "70vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "SUB_CATEGORY_ID",
      columnName: "Sub Category ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "BILLER_ID",
      columnName: "Biller ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "SUB_CATEGORY_ID",
      columnName: "Sub Category ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "BILLER_ID",
      columnName: "Biller ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "BILLER_NAME",
      columnName: "Biller Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "BILLER_DESC",
      columnName: "Biller Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "SUB_CATEGORY_NAME",
      columnName: "Sub Category Name",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "SUB_CATEGORY_DESC",
      columnName: "Sub Category Description",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "BILLER_INFO_URL",
      columnName: "Biller Info URL",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 150,
      maxWidth: 350,
    },
    {
      accessor: "BILLER_PAYMENT_URL",
      columnName: "Biller Payment URL",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 150,
      maxWidth: 350,
    },
  ],
};
