import { GridMetaDataType } from "components/dataTableStatic";
export const TempGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Temp",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "A/C P",
      accessor: "2",
      sequence: 2,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "From Eff. Date",
      accessor: "3",
      sequence: 3,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "To Eff. Date",
      accessor: "4",
      sequence: 4,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Code Description",
      accessor: "5",
      sequence: 5,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Amount Upto",
      accessor: "6",
      sequence: 6,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Active",
      accessor: "7",
      sequence: 7,
      componentType: "default",
      width: 80,
    },
  ],
};
