import { GridMetaDataType } from "components/dataTableStatic";
export const ATMLocMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ATM Location Master",
    rowIdColumn: "TERMINAL_ID",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "TERMINAL_ID",
      columnName: "ATM Terminal ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "ATM_NM",
      columnName: "ATM Location Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DIST_CD",
      columnName: "District Code",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "TERMINAL_ID",
      columnName: "ATM Terminal ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "ATM_NM",
      columnName: "ATM Location Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "ADD1",
      columnName: "Address 1",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 400,
      minWidth: 300,
      maxWidth: 500,
      showTooltip: true,
    },
    {
      accessor: "ADD2",
      columnName: "Address 2",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "ADD3",
      columnName: "Address 3",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "DIST_CD",
      columnName: "District code",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "POSTAL_CODE",
      columnName: "Postal code",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "LATITUDE",
      columnName: "Latitude",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "LONGITUDE",
      columnName: "Longitude",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "ACTIVE",
      columnName: "Active Status",
      sequence: 11,
      alignment: "left",
      isVisible: false,
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "ACTIVE_STATUS",
      columnName: "Active Status",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
  ],
};
