import { GridMetaDataType } from "components/dataTableStatic";
import { MasterDetailsMetaData } from "components/formcomponent/masterDetails/types";

export const DocumentGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Documents",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "DOC_DESCRIPTION",
      columnName: "Document*",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      isReadOnly: true,
      // options: [{label: "label1", value: "value1"},{label: "label2", value: "value2"}],
    //   options: (dependentValue, formState, _, authState) => {
    //       console.log("fwezzzzfeqw", dependentValue, formState, _, authState)
    //       // API.getDocumentTypes({COMP_CD: COMP_CD, CONSTITUTION: CONSTITUTION, CUST_TYPE: CUST_TYPE})
    //   },
      // options: [
      //   {label: "option1", value: "option1"},
      //   {label: "option2", value: "option2"},
      //   {label: "option3", value: "option3"},
      // ],
      // _optionsKey: "GetChargeTemplates",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "SUBMIT",
      columnName: "Submit",
      sequence: 3,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      placeholder: "",
      width: 100,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "DOCUMENT_NO",
      columnName: "Document No.",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
      isReadOnly: true,
    },  
    {
      accessor: "DOC_WEIGHTAGE",
      columnName: "Document Weightage",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
      isReadOnly: true,
    },  
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 2250,
      minWidth: 200,
      maxWidth: 400,
      isReadOnly: true,
    },  
    // {
    //   accessor: "VALID_DT_APPLICABLE",
    //   columnName: "VALID DATE APPLICABLE",
    //   componentType: "hidden",
    //   sequence: 7,
    // },
    {
      accessor: "VALID_TILL_DATE",
      columnName: "Valid till Date",
      sequence: 6,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      defaultValue: new Date(),
      // options: () => GeneralAPI.GetChargeTemplates(),
      // options: [{label: "label1", value: "value1"},{label: "label2", value: "value2"}],
      // _optionsKey: "GetChargeTemplates",
      // placeholder: "",
      width: 250,
      minWidth: 250,
      maxWidth: 400,
    },
    // {
    //   accessor: "SUBMIT_BTN",
    //   columnName: "Action",
    //   componentType: "buttonRowCell",
    //   sequence: 4,
    //   buttonLabel: "EDIT/VIEW",
    //   isVisible: true,
    //   width: 140,
    //   minWidth: 140,
    //   maxWidth: 200,
    //   __EDIT__: { isVisible: true },
    // },
    {
      columnName: "",
      componentType: "deleteRowCell",
      // accessor: "_hidden",
      accessor: "_hidden",
      buttonLabel: "Submit",
      shouldExclude:(initialValue,original,prevRows,nextRows)=>{
        if(original?.IS_MANDATORY==='Y'){
          return true;
        }
        return false;
      },
      sequence: 9,
      width: 100,
      minWidth: 80,
      maxWidth: 400,
      // shouldExclude: () => {

      // },
      // isVisible: false,
      __EDIT__: { isVisible: true },
    },
    // {

    // }
    // {
    //   accessor: "ENTERED_DATE",
    //   columnName: "Entered Date",
    //   sequence: 8,
    //   alignment: "left",
    //   componentType: "date",
    //   dateFormat: "dd/MM/yyyy",
    //   defaultValue: new Date(),
    //   placeholder: "",
    //   width: 250,
    //   minWidth: 250,
    //   maxWidth: 400,
    // },
    // {
    //   columnName: "",
    //   componentType: "buttonRowCell",
    //   accessor: "UPLOAD_FILE",
    //   sequence: 11,
    //   buttonLabel: "Upload",
    //   width: 250,
    //   minWidth: 250,
    //   maxWidth: 400,
    //   isVisible: false,
    //   __EDIT__: { isVisible: true },
    // },
    // {
    //   columnName: "Action",
    //   componentType: "deleteRowCell",
    //   accessor: "_hidden",
    //   sequence: 12,
    //   width: 250,
    //   minWidth: 250,
    //   maxWidth: 400,
    //   isVisible: false,
    //   __EDIT__: { isVisible: true },
    // },
    
    // {
    //   accessor: "BTN",
    //   columnName: "Action",
    //   componentType: "buttonRowCell",
    //   sequence: 9,
    //   buttonLabel: "Upload",
    //   isVisible: true,
    //   width: 140,
    //   minWidth: 140,
    //   maxWidth: 200,
    //   __EDIT__: { isVisible: true },
    // },
    // {
    //   columnName: "",
    //   componentType: "deleteRowCell",
    //   accessor: "SPECIAL_AMOUNT",
    //   sequence: 10,
    //   buttonLabel: "Special Amount",
    //   isVisible: true,
    //   width: 140,
    //   minWidth: 140,
    //   maxWidth: 200,
    //   // __EDIT__: { isVisible: true },
    //   // __VIEW__: { isVisible: true },
    //   // __NEW__: { isVisible: true },
    // },
  ],
};
