import { GridMetaDataType } from "components/dataTableStatic";
export const StopPayGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Stop Payment Detail",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Intimate Date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_FROM",
      columnName: "Cheque From",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 60,
      maxWidth: 150,
      isVisible: true,
    },
    {
      accessor: "CHEQUE_TO",
      columnName: "Cheque To",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 90,
      minWidth: 60,
      maxWidth: 120,
      isVisible: true,
    },
    {
      accessor: "CHEQUE_DT",
      columnName: "Cheque Date",
      sequence: 4,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "CHEQUE_AMOUNT",
      columnName: "Cheque Amount",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 50,
      maxWidth: 180,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "FLAG",
      columnName: "Flag",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 80,
      minWidth: 60,
      maxWidth: 100,
    },
  ],
};
