import { GridMetaDataType } from "components/dataTableStatic";
export const DocumentGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Document",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Submitted",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Document",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_FROM",
      columnName: "Valid Upto",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      isVisible: true,
    },
    {
      accessor: "CHEQUE_TO",
      columnName: "Entered Form",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_TOTAL",
      columnName: "Document Type",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 220,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "UNUSED_CHQ",
      columnName: "Document Amount",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "AMOUNT",
      columnName: "View",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
  ],
};
