import { GridMetaDataType } from "components/dataTableStatic";
export const EmailSMSTemplateGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Email/SMS Template Configuration",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "MAIL_TYPE",
      columnName: "Tran. Type",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "MAIL_SUBJECT",
      columnName: "Mail Subject",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "MAIL_TYPE",
      columnName: "Tran. Type",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 350,
      minWidth: 200,
      maxWidth: 500,
      showTooltip: true,
    },
    {
      accessor: "EFFECTIVE_FROM_DT",
      columnName: "Effective From",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
      showTooltip: true,
    },
    {
      accessor: "MAIL_SUBJECT",
      columnName: "Mail Subject",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 330,
      minWidth: 200,
      maxWidth: 500,
      showTooltip: true,
    },
  ],
};
