import { GridMetaDataType } from "components/dataTableStatic";
export const CheckBookGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ChequeBook Details",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "sr",
      columnName: "Sr.",
      sequence: 1,
      componentType: "default",
      width: 70,
    },
    {
      accessor: "is dt",
      columnName: "Issue Date",
      sequence: 2,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "auto Issue",
      columnName: "Auto Issue",
      sequence: 3,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "from chq",
      columnName: "From CHQ No.",
      sequence: 4,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "to chq",
      columnName: "To CHQ No.",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "CHQ",
      columnName: "No. of CHQ(s) ",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "Charge",
      columnName: "Charge",
      sequence: 7,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "GST",
      columnName: "GST",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "Remarks",
      columnName: "Remarks",
      sequence: 9,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "Characteristics",
      columnName: "Characteristics",
      sequence: 10,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "At",
      columnName: "At Par",
      sequence: 11,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "Requisition",
      columnName: "Requisition",
      sequence: 12,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "Pending",
      columnName: "Pending",
      sequence: 13,
      componentType: "default",
      width: 120,
    },
  ],
};
