import { GridMetaDataType } from "components/dataTableStatic";
export const FD_gridData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "FD Detail",
    rowIdColumn: "FD_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "ACCOUNT_NUMBER",
      columnName: "Account No.",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 140,
    },
    {
      accessor: "FD_NO",
      columnName: "FD Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 85,
      minWidth: 70,
      maxWidth: 150,
    },
    {
      accessor: "BALANCE_AMT",
      columnName: "Balance",
      sequence: 3,
      alignment: "right",
      componentType: "currency",
      width: 105,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "PRINCIPAL_AMT",
      columnName: "Principal Amount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      isVisible: true,
    },
    {
      accessor: "RATE",
      columnName: "Rate%",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 55,
      minWidth: 50,
      maxWidth: 80,
    },
    {
      accessor: "MATURITY_AMT",
      columnName: "Maturity Amount",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 116,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "MATURITY_DATE",
      columnName: "Maturity Date",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "DEPOSITE_DATE",
      columnName: "Deposite Date",
      sequence: 7,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "ISSUE_DATE",
      columnName: "Issue Date",
      sequence: 8,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 104,
      minWidth: 100,
      maxWidth: 150,
    },
  ],
};
export const NSC_gridData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "NSC Detail",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "CERTI_NO",
      columnName: "Cetificate No.",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "COLLATERAL_NAME",
      columnName: "Collateral Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "COLLATERAL_AMT",
      columnName: "Collateral Amount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 124,
      minWidth: 100,
      maxWidth: 150,
    },

    {
      accessor: "COLLATERAL_RATE",
      columnName: "Collateral Rate%",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 115,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 6,
      alignment: "center",
      componentType: "date",

      dateFormat: "dd/MM/yyyy",
      width: 115,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "EXP_DATE",
      columnName: "Expiry Date",
      sequence: 7,
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      componentType: "date",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ISSUE_COMPANY",
      columnName: "Issue Company",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "ISSUE_DATE",
      columnName: "Issue Date",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "LIEN_ACCT_TYPE",
      columnName: "Account Type",
      sequence: 10,
      alignment: "center",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "LIEN_ACCT_CD",
      columnName: "Account No.",
      sequence: 11,
      alignment: "center",
      componentType: "default",
      width: 90,
      minWidth: 70,
      maxWidth: 130,
    },
    {
      accessor: "MATURED_AMT",
      columnName: "Matured Amount",
      sequence: 12,
      alignment: "right",
      componentType: "currency",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "PERIOD_NO",
      columnName: "Period No.",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 83,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "REGISTRATION_NO",
      columnName: "Registration No.",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 115,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "REMARK",
      columnName: "Remarks",
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};

export const NSC_FormMetaData = {
  form: {
    name: "nscDeatil",
    label: "NSC Detail",
    resetFieldOnUnmount: false,
    validationRun: "onBlur",
    submitAction: "home",
    hideHeader: true,
    render: {
      ordering: "auto",
      // ordering: "sequence",
      renderType: "simple",
      gridConfig: {
        item: {
          xs: 12,
          sm: 4,
          md: 4,
        },
        container: {
          direction: "row",
          spacing: 1,
          height: "35vh",
        },
      },
    },
    componentProps: {
      textField: {
        fullWidth: true,
      },
      select: {
        fullWidth: true,
      },
      datePicker: {
        fullWidth: true,
      },
      numberFormat: {
        fullWidth: true,
      },
      inputMask: {
        fullWidth: true,
      },
      datetimePicker: {
        fullWidth: true,
      },
    },
  },
  fields: [
    {
      render: {
        componentType: "textField",
      },
      name: "SECURITY_CD",
      label: "Security Code",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "textField",
      },
      name: "CERTI_NO",
      label: "Certificate No.",
      type: "text",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "textField",
      },
      name: "COLLATERAL_NAME",
      label: "Account Name",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 4.8,
        sm: 4.8,
        lg: 4.8,
        xl: 4.8,
      },
    },
    {
      render: {
        componentType: "datePicker",
      },
      name: "ISSUE_DATE",
      label: "Issue Date",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },
    {
      render: {
        componentType: "textField",
      },
      name: "PERIOD_NO",
      label: "Period No.",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "amountField",
      },
      name: "COLLATERAL_AMT",
      label: "Collateral Amount",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "rateOfInt",
      },
      name: "COLLATERAL_RATE",
      label: "Collateral Rate%",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },
    {
      render: {
        componentType: "amountField",
      },
      name: "MATURED_AMT",
      label: "Matured Amount",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "datePicker",
      },
      name: "EXP_DATE",
      label: "Expirt Date",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },
    {
      render: {
        componentType: "textField",
      },
      name: "ISSUE_COMPANY",
      label: "Issue Company",
      placeholder: "Issue Company ",
      isReadOnly: true,
      type: "text",
      sequence: 0,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "textField",
      },
      name: "REGISTRATION_NO",
      label: "Registration No",
      placeholder: "Registration No",
      isReadOnly: true,
      type: "text",
      sequence: 0,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "textField",
      },
      name: "LIEN_YES_NO",
      label: "Lien Yes No",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.4,
        sm: 2.4,
        lg: 2.4,
        xl: 2.4,
      },
    },

    {
      render: {
        componentType: "Remark",
      },
      name: "REMARK",
      label: "Remarks",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 4.8,
        sm: 4.8,
        lg: 4.8,
        xl: 4.8,
      },
    },
  ],
};
