import { GridMetaDataType } from "components/dataTableStatic";
export const limitEntryGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Limit Detail",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "53vh",
      max: "53vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    footerNote: "Note : Double-click on Pink row to force-expire the limit.",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    // {
    //   accessor: "BRANCH_CD",
    //   columnName: "Branch Code",
    //   sequence: 2,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    //   isVisible: false,
    // },
    // {
    //   accessor: "ACCT_TYPE",
    //   columnName: "Account Type",
    //   sequence: 3,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    //   isVisible: false,
    // },
    // {
    //   accessor: "ACCT_CD",
    //   columnName: "Account No",
    //   sequence: 4,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    //   isVisible: false,
    // },

    {
      accessor: "ENTRY_DT",
      columnName: "Entry Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Effective Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "EXPIRY_DT",
      columnName: "Expiry Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 105,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "INT_RATE",
      columnName: "Int. Rate%",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 78,
      minWidth: 60,
      maxWidth: 100,
    },

    {
      accessor: "MARGIN",
      columnName: "Margin%",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 72,
      minWidth: 60,
      maxWidth: 100,
    },
    {
      accessor: "SECURITY_VALUE",
      columnName: "Security Value",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 104,
      minWidth: 100,
      maxWidth: 150,
      isVisible: true,
    },
    {
      accessor: "LIMIT_AMOUNT",
      columnName: "Limit Amount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },

    {
      accessor: "FD_DESC",
      columnName: "FD Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 275,
      minWidth: 200,
      maxWidth: 300,
    },
    {
      accessor: "RESOLUTION_DATE",
      columnName: "Resolution Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      width: 133,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ALLOW_DELETE",
      columnName: "Action",
      buttonLabel: "Remove",

      sequence: 4,
      alignment: "center",
      componentType: "buttonRowCell",
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (initialValue === "Y") {
          return false;
        }
        return true;
      },
      width: 90,
      minWidth: 60,
      maxWidth: 130,
    },

    // {
    //   accessor: "FD_BRANCH_CD",
    //   columnName: "FD-Branch",
    //   sequence: 4,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "FD_TYPE",
    //   columnName: "FD-Type",
    //   sequence: 4,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "FD_ACCT_CD",
    //   columnName: "FD-A/c No.",
    //   sequence: 4,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "FD_NO",
    //   columnName: "FD No.",
    //   sequence: 4,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },

    // {
    //   accessor: "PENAL_RATE",
    //   columnName: "Penal Rate",
    //   sequence: 6,
    //   alignment: "right",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 400,
    // },

    // {
    //   accessor: "DRAWING_POWER",
    //   columnName: "Drawing Power",
    //   sequence: 8,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "REMARKS",
    //   columnName: "Remarks",
    //   sequence: 9,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 150,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },

    // {
    //   accessor: "TRAN_CD",
    //   columnName: "Tran CD",
    //   sequence: 9,
    //   alignment: "left",
    //   componentType: "date",
    //   width: 150,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "CONFIRMED",
    //   columnName: "Status",
    //   sequence: 10,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "EXPIRED_FLAG",
    //   columnName: "Expired-Flag",
    //   sequence: 10,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "ENTERED_DATE",
    //   columnName: "Entered DT",
    //   sequence: 10,
    //   alignment: "center",
    //   componentType: "date",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "ENTERED_BY",
    //   columnName: "Entered By",
    //   sequence: 10,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "LAST_ENTERED_BY",
    //   columnName: "Entered By",
    //   sequence: 10,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "LAST_MODIFIED_DATE",
    //   columnName: "Last-Modified DT",
    //   sequence: 10,
    //   alignment: "left",
    //   componentType: "date",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "LAST_MACHINE_NM",
    //   columnName: "Last Machine NM",
    //   sequence: 10,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "VERIFIED_BY",
    //   columnName: "verified by",
    //   sequence: 10,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "MACHINE_NM",
    //   columnName: "Machine NM",
    //   sequence: 10,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
  ],
};
