import { GridMetaDataType } from "components/dataTableStatic";
export const limitEntryGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Limit Detail",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "53vh",
      max: "53vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    footerNote: "Note : Double-click on Pink row to force-expire the limit.",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "ENTRY_DT",
      columnName: "Entry Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Effective Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "EXPIRY_DT",
      columnName: "Expiry Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 105,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "INT_RATE",
      columnName: "Int. Rate%",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 78,
      minWidth: 60,
      maxWidth: 100,
    },

    {
      accessor: "MARGIN",
      columnName: "Margin%",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 72,
      minWidth: 60,
      maxWidth: 100,
    },
    {
      accessor: "SECURITY_VALUE",
      columnName: "Security Value",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 104,
      minWidth: 100,
      maxWidth: 150,
      isVisible: true,
    },
    {
      accessor: "LIMIT_AMOUNT",
      columnName: "Limit Amount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 90,
      maxWidth: 150,
    },

    {
      accessor: "FD_DESC",
      columnName: "FD Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 275,
      minWidth: 200,
      maxWidth: 300,
    },
    {
      accessor: "RESOLUTION_DATE",
      columnName: "Resolution Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      width: 133,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CONFIRMED",
      columnName: "Status",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 101,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "ALLOW_DELETE",
      columnName: "Action",
      buttonLabel: "Remove",

      sequence: 4,
      alignment: "center",
      componentType: "buttonRowCell",
      shouldExclude: (initialValue) => {
        if (initialValue === "Y") {
          return false;
        }
        return true;
      },
      width: 90,
      minWidth: 60,
      maxWidth: 130,
    },
  ],
};
