import { GridMetaDataType } from "components/dataTableStatic";
export const BranchMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Branch Master",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "BRANCH_CD",
      columnName: "Branch Code",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "BRANCH_NM",
      columnName: "Branch Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DIST_CD",
      columnName: "District Code",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch Code",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "BRANCH_NM",
      columnName: "Branch Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "DIST_CD",
      columnName: "District Code",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
      showTooltip: true,
    },
    {
      accessor: "ADD1",
      columnName: "Address",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "CONTACT1",
      columnName: "Contact Number",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      showTooltip: true,
    },
    {
      accessor: "E_MAIL_ID",
      columnName: "Email ID",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "ACTIVE_STATUS",
      columnName: "Active",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
      showTooltip: true,
    },
  ],
};
