import { GridMetaDataType } from "@acuteinfo/common-base";
export const RecurringPaymentEntryGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 30, 50],
    defaultPageSize: 10,
    containerHeight: {
      min: "77vh",
      max: "77vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccountType",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_CD",
      columnName: "AccountNum",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_NM",
      columnName: "accountName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 310,
      minWidth: 300,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "TDS_AMT",
      columnName: "CalcTDS",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 130,
    },
    {
      accessor: "TRF_AMT",
      columnName: "Transfer",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "TOKEN_NO",
      columnName: "CashPaymentTokenNo",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 200,
      minWidth: 160,
      maxWidth: 250,
    },
    {
      accessor: "CASH_AMT",
      columnName: "Cash",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "PAYSLIP",
      columnName: "ByPayslipDD",
      sequence: 10,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 110,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "RTGS_NEFT",
      columnName: "ByNEFT",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 110,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "PAYMENT_AMT",
      columnName: "PaymentAmount",
      sequence: 12,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "CONF_STATUS",
      columnName: "Status",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
  ],
};
