import { GridMetaDataType } from "components/dataTableStatic";
export const ParametersGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Parameter Master",
    rowIdColumn: "PARA_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "PARA_CD",
      columnName: "Code",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "PARA_CD",
      columnName: "Code",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 150,
      //isAutoSequence: true,
    },
    {
      accessor: "PARA_NM",
      columnName: "Description",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 400,
      minWidth: 200,
      maxWidth: 600,
    },
    {
      accessor: "DIS_DATATYPE_CD",
      columnName: "Datatype",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "PARA_VALUE",
      columnName: "Value",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 450,
      minWidth: 250,
      maxWidth: 600,
    },
    // {
    //   accessor: "CONFIRM_STATUS",
    //   columnName: "Confirm Status",
    //   sequence: 7,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 230,
    //   minWidth: 220,
    //   maxWidth: 300,
    // },
    // {
    //   accessor: "LAST_ENTERED_BY",
    //   columnName: "Modified By",
    //   sequence: 8,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 150,
    //   minWidth: 140,
    //   maxWidth: 180,
    // },
    // {
    //   accessor: "LAST_MODIFIED_DATE",
    //   columnName: "Modified Date",
    //   sequence: 9,
    //   alignment: "center",
    //   componentType: "date",
    //   dateFormat: "dd/MM/yyyy",
    //   width: 120,
    //   minWidth: 120,
    //   maxWidth: 150,
    // },
  ],
};
