import { GridMetaDataType } from "components/dataTableStatic";

export const MerchantOnboardingGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Merchant Onboarding Configuration",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 440,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "MERCHANT_ID_DISP",
      columnName: "Merchant ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "TERMINAL_ID_DISP",
      columnName: "Terminal ID",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
    },

    {
      accessor: "PID",
      columnName: "Gateway Username",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "CONFIRMED_STATUS",
      columnName: "Confirm Status",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 180,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 110,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 7,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 90,
      maxWidth: 180,
    },
  ],
};
