import { GridMetaDataType } from "components/dataTableStatic";

export const MarqueMessageGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Marquee Text Configuration",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 440,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "CHANNEL_DISP",
      columnName: "Channel",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 60,
      maxWidth: 150,
    },
    {
      accessor: "MSG_ALERT",
      columnName: "Marquee Text (English)",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 350,
      minWidth: 280,
      maxWidth: 350,
    },
    {
      accessor: "MSG_ALERT_BN",
      columnName: "Marquee Text (Local)",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 350,
      minWidth: 280,
      maxWidth: 350,
    },
    {
      accessor: "VALID_FROM_DT",
      columnName: "Effective From",
      sequence: 4,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy hh:mm a",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "VALID_TO_DT",
      columnName: "Effective To",
      sequence: 5,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy hh:mm a",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "STATUS",
      columnName: "Status",
      sequence: 6,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      placeholder: "",
      width: 90,
      minWidth: 120,
      maxWidth: 100,
    },
  ],
};
