import { GridMetaDataType } from "components/dataTableStatic";
export const LienGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Lien Detail",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "REMOVAL_DT",
      columnName: "Removal Date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "LIEN_AMOUNT",
      columnName: "Lien Amount",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 60,
      maxWidth: 150,
      isVisible: true,
    },
    {
      accessor: "LIEN_STATUS",
      columnName: "Status",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 90,
      minWidth: 60,
      maxWidth: 120,
      isVisible: true,
    },
    {
      accessor: "CONFIRMED",
      columnName: "Confirmed",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "LIEN_REASON_CD",
      columnName: "Reason",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 50,
      maxWidth: 180,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "Verified By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 400,
    },
  ],
};
