import { GridMetaDataType } from "components/dataTableStatic";
export const LienGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Lien Detail",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    searchPlaceholder: "Lien Detail",
    // footerNote:"",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 80,
      minWidth: 70,
      maxWidth: 130,
      isAutoSequence: true,
    },
    {
      accessor: "LIEN_CD",
      columnName: "Lien Code",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 50,
      maxWidth: 180,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 215,
      minWidth: 150,
      maxWidth: 240,
    },

    {
      accessor: "EFECTIVE_DT",
      columnName: "Effective Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "REMOVAL_DT",
      columnName: "Removal Date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 130,
    },
    {
      accessor: "LIEN_AMOUNT",
      columnName: "Lien Amount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 60,
      maxWidth: 150,
    },
    {
      accessor: "LIEN_STATUS",
      columnName: "Status",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 90,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "CONFIRMED",
      columnName: "Confirmed",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 101,
      minWidth: 80,
      maxWidth: 150,
    },

    {
      accessor: "LIEN_REASON_CD",
      columnName: "Reason",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 230,
      minWidth: 150,
      maxWidth: 350,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 85,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "Verified By",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 85,
      minWidth: 70,
      maxWidth: 120,
    },
  ],
};
