import { GridMetaDataType } from "components/dataTableStatic";
export const CustomerSearchingGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Customer Searching",
    rowIdColumn: "USER_NAME",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "42vh",
      max: "50vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
  },
  filters: [],
  columns: [
    {
      accessor: "sr_no",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "USER_NAME",
      columnName: "Login ID",
      sequence: 0,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      isVisible: false,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CUST_NAME",
      columnName: "Customer Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "REG_CARD_ACCT_NO",
      columnName: "Primary Account/Card Number",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "PRIMARY_APP_SOURCE",
      columnName: "Primary Source",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "PRIMARY_CBNUMBER",
      columnName: "Primary CB Number",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "STATUS",
      columnName: "STATUS",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      color: (value) => {
        if ((value || "unlock").toLowerCase() === "unlock") {
          return "green";
        }
        return "red";
      },
    },
    {
      accessor: "AUTH_FLAG",
      columnName: "Auth. Flag",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "MOBILE_NO",
      columnName: "Mobile Number",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "MAIL_ID",
      columnName: "Email ID",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },
  ],
};
