import { GridMetaDataType } from "components/dataTableStatic";
export const LoanClosureReqGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Loan Closure Request",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "63vh",
      max: "70vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
      //isAutoSequence: true,
    },
    {
      accessor: "USER_ID",
      columnName: "User ID",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 160,
    },
    {
      accessor: "APPLICANT_NM",
      columnName: "Customer Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 220,
      maxWidth: 400,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Closure Date",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "LOAN_ACCT_CD",
      columnName: "Loan Account",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "AMOUNT",
      columnName: "Amount",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "FROM_ACCT_NO",
      columnName: "From Account",
      sequence: 8,
      alignment: "Left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
