import { GridMetaDataType } from "components/dataTableStatic";

export const AdvocateMstGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "CODE",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 40, 60],
    defaultPageSize: 20,
    containerHeight: {
      min: "77vh",
      max: "77vh",
    },
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "CODE",
      columnName: "Code",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "AdvocateName",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 280,
      minWidth: 260,
      maxWidth: 350,
      showTooltip: true,
    },
    {
      accessor: "CONTACT1",
      columnName: "MobileNo",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 160,
      maxWidth: 200,
    },
    {
      accessor: "ADD1",
      columnName: "Address",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 280,
      minWidth: 260,
      maxWidth: 350,
      showTooltip: true,
    },
    {
      accessor: "EMAIL",
      columnName: "EmailID",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 280,
      minWidth: 260,
      maxWidth: 350,
      showTooltip: true,
    },
  ],
};
