import { GridMetaDataType } from "components/dataTableStatic";
export const StockGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Stock",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "St. Date",
      accessor: "1",
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 100,
    },
    {
      columnName: "Stock Till Date",
      accessor: "2",
      sequence: 3,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Stock Desc",
      accessor: "3",
      sequence: 3,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Margin",
      accessor: "4",
      sequence: 4,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Stock Value",
      accessor: "5",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Drawing Power",
      accessor: "6",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Security Desc",
      accessor: "7",
      sequence: 7,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Entered Dt",
      accessor: "8",
      sequence: 8,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Recieved Dt",
      accessor: "9",
      sequence: 9,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
  ],
};
