import { GridMetaDataType } from "@acuteinfo/common-base";
export const StockGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Stock",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    hideHeader: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "St. Date",
      accessor: "TRAN_DT", //
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 100,
    },
    {
      columnName: "Stock Till Date",
      accessor: "WITHDRAW_DT",
      sequence: 3,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Stock Desc",
      accessor: "STOCK_DESC",
      sequence: 3,
      componentType: "default",
      width: 150,
    },
    {
      columnName: "Margin",
      accessor: "MARGIN",
      sequence: 4,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Stock Value",
      accessor: "STOCK_VALUE",
      sequence: 5,
      componentType: "default",
      width: 100,
      alignment: "right",
    },
    {
      columnName: "Drawing Power",
      accessor: "DRAWING_POWER",
      sequence: 6,
      componentType: "default",
      width: 120,
      alignment: "right",
    },
    {
      columnName: "Security Desc",
      accessor: "SECURITY_CD",
      sequence: 7,
      componentType: "default",
      width: 120,
      alignment: "right",
    },
    {
      columnName: "Entered Dt",
      accessor: "ENTERED_DATE",
      sequence: 8,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Recieved Dt",
      accessor: "RECEIVED_DT",
      sequence: 9,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Max Ason Dt",
      accessor: "ASON_DT",
      sequence: 10,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
  ],
};
