import { GridMetaDataType } from "components/dataTableStatic";
export const DisbursementGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Disbursement",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Effective Date",
      accessor: "RATE_WEF",
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Disbursement Date",
      accessor: "DISBURSEMENT_DT",
      sequence: 3,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Disbursement Amount",
      accessor: "DISBURSEMENT_AMT",
      sequence: 4,
      componentType: "currency",
      width: 120,
    },
    {
      columnName: "Installment Type",
      accessor: "INSTALLMENT_TYPE",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "No. of Inst.",
      accessor: "INST_NO",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Instalment Amount",
      accessor: "INST_RS",
      sequence: 7,
      componentType: "currency",
      width: 120,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Next Installment Start Date",
      accessor: "INS_START_DT",
      sequence: 9,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Int. Rate",
      accessor: "INT_RATE",
      sequence: 10,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Entered Date",
      accessor: "ENTERED_DATE",
      sequence: 11,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
  ],
};
