import { GridMetaDataType } from "components/dataTableStatic";

export const UserProfileMetaData = {
  form: {
    name: "profile",
    label: "User Profile",
    resetFieldOnUnmount: false,
    validationRun: "onBlur",
    render: {
      ordering: "auto",
      renderType: "simple",
      gridConfig: {
        item: {
          xs: 12,
          sm: 3,
          md: 3,
        },
        container: {
          direction: "row",
          spacing: 2,
        },
      },
    },
    componentProps: {
      datePicker: {
        fullWidth: true,
      },
      select: {
        fullWidth: true,
      },
      textField: {
        fullWidth: true,
      },
      numberFormat: {
        fullWidth: true,
      },
    },
  },
  fields: [
    {
      render: { componentType: "textField", group: 0 },
      name: "USER_NAME",
      sequence: 1,
      type: "text",
      label: "User ID",
      isReadOnly: true,
      placeholder: "First Name",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "NAME",
      sequence: 2,
      type: "text",
      label: "Name",
      isReadOnly: true,
      placeholder: "Name",
      GridProps: { xs: 12, md: 6, sm: 6 },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "USER_LEVEL",
      sequence: 3,
      type: "text",
      label: "User Level",
      isReadOnly: true,
      placeholder: "User Level",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },

    {
      render: { componentType: "phoneNumber", group: 0 },
      name: "CONTACT2",
      sequence: 4,
      type: "text",
      label: "Mobile Number",
      isReadOnly: false,
      required: true,
      placeholder: "Mobile Number",
      GridProps: { xs: 12, md: 3, sm: 3 },
      StartAdornment: "+88",
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "EMAIL_ID",
      sequence: 5,
      type: "text",
      label: "Email ID",
      isReadOnly: false,
      placeholder: "Email ID",
      GridProps: { xs: 12, md: 6, sm: 6 },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "GROUP_NAME",
      sequence: 6,
      type: "text",
      label: "User Group",
      isReadOnly: true,
      placeholder: "User Group",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "checkbox", group: 0 },
      name: "ALLOW_RELEASE",
      sequence: 9,
      type: "text",
      label: "Allowed Release",
      isReadOnly: true,
      placeholder: "Allowed Release",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "BRANCH_NAME",
      sequence: 8,
      type: "text",
      label: "Branch Name",
      isReadOnly: true,
      placeholder: "Branch Name",
      GridProps: { xs: 12, md: 6, sm: 6 },
    },
  ],
};

export const UserLoginDtlGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "User Login Details",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    hideFooter: true,
    disableGroupBy: true,
    enablePagination: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "30vh",
      max: "33vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "USERNAME",
      columnName: "Login ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "LOGIN_DT",
      columnName: "Login Date",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 250,
    },
    {
      accessor: "USER_FLAG",
      columnName: "Login Flag",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "LOGOUT_DT",
      columnName: "Logout Date",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 250,
    },
    {
      accessor: "REMARKS",
      columnName: "Activity Remarks",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "IP_ADDR",
      columnName: "IP Address",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "RELEASED_USER_NAME",
      columnName: "Released User",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "RELEASED_DT",
      columnName: "Released Date",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 250,
    },
  ],
};
