import { GridMetaDataType } from "components/dataTableStatic";
export const AgentMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: false,
    gridLabel: "Agent Master (MST/041)",
    rowIdColumn: "AGENT_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 30, 50],
    defaultPageSize: 10,
    containerHeight: {
      min: "77vh",
      max: "77vh",
    },
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 40,
      maxWidth: 70,
      isAutoSequence: true,
    },
    {
      accessor: "AGENT_CD",
      columnName: "Code",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 40,
      maxWidth: 70,
    },
    {
      accessor: "AGENT_NM",
      columnName: "Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 160,
      maxWidth: 180,
    },
    {
      accessor: "GROUP_CD_NM",
      columnName: "Group",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 70,
      maxWidth: 90,
    },
    {
      accessor: "AGENT_BRANCH_CD",
      columnName: "Agent Account Branch",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 160,
    },
    {
      accessor: "AGENT_TYPE_CD",
      columnName: "Agent Account Type",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "AGENT_ACCT_CD",
      columnName: "Agent Account No.",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Agent Account Name",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "SECURITY_BRANCH",
      columnName: "Security Account Branch",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 150,
      maxWidth: 170,
    },
    {
      accessor: "SECURITY_TYPE_CD",
      columnName: "Security Account Type",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 160,
    },
    {
      accessor: "SECURITY_ACCT_CD",
      columnName: "Security Account No.",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "SECURITY_ACCT_NM",
      columnName: "Security Account Name",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 150,
      maxWidth: 170,
    },
    {
      accessor: "SECURITY_AMT",
      columnName: "Security Amount",
      sequence: 13,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 110,
      maxWidth: 130,
    },
    {
      accessor: "SECURITY_PER",
      columnName: "Security %",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 70,
      maxWidth: 90,
    },
    {
      accessor: "SECURITY_FLAG_DISP_VAL",
      columnName: "Security Calculation On",
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 150,
      maxWidth: 170,
    },
    {
      accessor: "OTH_BRANCH_CD",
      columnName: "Other Account Branch",
      sequence: 16,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 160,
    },
    {
      accessor: "OTH_ACCT_TYPE",
      columnName: "Other Account Type",
      sequence: 17,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "OTH_ACCT_CD",
      columnName: "Other Account No.",
      sequence: 18,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "OTHER_ACCT_NM",
      columnName: "Other Account Name",
      sequence: 19,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "PTAX_BRANCH_CD",
      columnName: "Professional Tax Account Branch",
      sequence: 20,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 200,
      maxWidth: 230,
    },
    {
      accessor: "PTAX_ACCT_TYPE",
      columnName: "Professional Tax Account Type",
      sequence: 21,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 190,
      maxWidth: 210,
    },
    {
      accessor: "PTAX_ACCT_CD",
      columnName: "Professional Tax Account No.",
      sequence: 22,
      alignment: "left",
      componentType: "default",
      width: 190,
      minWidth: 180,
      maxWidth: 200,
    },
    {
      accessor: "PTAX_ACCT_NM",
      columnName: "Professional Tax Account Name",
      sequence: 23,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 190,
      maxWidth: 210,
    },
    {
      accessor: "PTAX_DEF_TRAN_NM",
      columnName: "Professional Tax Account Configuration",
      sequence: 24,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 240,
      maxWidth: 260,
    },
    {
      accessor: "PIGMY_CONF_NM",
      columnName: "Hand Held Machine Configuration",
      sequence: 25,
      alignment: "left",
      componentType: "default",
      width: 230,
      minWidth: 220,
      maxWidth: 240,
    },
    {
      accessor: "TDS_RATE",
      columnName: "Hand Held Machine TDS Rate",
      sequence: 26,
      alignment: "left",
      componentType: "default",
      width: 190,
      minWidth: 180,
      maxWidth: 200,
    },
  ],
};
