import { GridMetaDataType } from "components/dataTableStatic";

export const TradeMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Trade Master",
    rowIdColumn: "TRADE_CD",
    defaultColumnConfig: {
      width: 440,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    // {
    //   accessor: "COMP_CD",
    //   columnName: "Company Code",
    //   sequence: 2,
    //   alignment: "left",
    //   componentType: "default",
    //   placeholder: "",
    //   width: 120,
    //   minWidth: 60,
    //   maxWidth: 150,
    // },
    {
      accessor: "TRADE_NM",
      columnName: "Description",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "CKYC_OCCUPATION",
      columnName: "C-kyc Group",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      isReadOnly: true,
      placeholder: "",
      width: 100,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "C_KYC_OCCUPATION_NM",
      columnName: "C-kyc Group Name",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      isReadOnly: true,
      placeholder: "",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "CONSTITUTION_TYPE",
      columnName: "Constitution",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      isReadOnly: true,
      placeholder: "",
      width: 120,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "CONSTITUTION_TYPE_NM",
      columnName: "Constitution Name",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      isReadOnly: true,
      placeholder: "",
      width: 120,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Enter By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      isReadOnly: true,
      placeholder: "",
      width: 90,
      minWidth: 120,
      maxWidth: 100,
    },
  ],
};
