import { GridMetaDataType } from "components/dataTableStatic";
export const JointDetailGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Joint Details",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Joint Name Infor Type",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_FROM",
      columnName: "Person Name",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      isVisible: true,
    },
    {
      accessor: "CHEQUE_TO",
      columnName: "Designation",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_TOTAL",
      columnName: "MEM Type A/C No.",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 220,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "UNUSED_CHQ",
      columnName: "Reference Account",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "AMOUNT",
      columnName: "Contact No.",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "SERVICE_TAX",
      columnName: "Customer Id",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
