import { GridMetaDataType } from "components/dataTableStatic";
export const JointDetailGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Joint Details",
    rowIdColumn: "id",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "id1",
      columnName: "Sr.",
      sequence: 1,
      componentType: "default",
      isAutoSequence: true,
    },
    {
      accessor: "ACCT_CD",
      columnName: "ACCT No",
      sequence: 2,
      componentType: "default",
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "ACCT_TYPE",
      sequence: 3,
      componentType: "default",
    },
    {
      accessor: "BRANCH_CD",
      columnName: "BRANCH_CD",
      sequence: 4,
      componentType: "default",
    },
    {
      accessor: "COMP_CD",
      columnName: "COMP_CD",
      sequence: 5,
      componentType: "default",
    },
    {
      accessor: "REF_PERSON_NAME",
      columnName: "REF_PERSON_NAME ",
      sequence: 6,
      componentType: "default",
    },
    {
      accessor: "DESIGNATION_NM",
      columnName: "DESIGNATION_NM ",
      sequence: 7,
      componentType: "default",
    },
    {
      accessor: "ADD1",
      columnName: "Address",
      sequence: 8,
      componentType: "default",
    },

    {
      accessor: "PIN_CODE",
      columnName: "Pin Code",
      sequence: 9,
      componentType: "default",
    },
    {
      accessor: "J_TYPE",
      columnName: "J_TYPE",
      sequence: 10,
      componentType: "default",
    },
    {
      accessor: "PHONE",
      columnName: "PHONE",
      sequence: 11,
      componentType: "default",
    },
    {
      accessor: "BIRTH_DATE",
      columnName: "BIRTH_DATE",
      sequence: 12,
      componentType: "default",
    },
    {
      accessor: "REF_BRANCH_CD",
      columnName: "REF_BRANCH_CD",
      sequence: 13,
      componentType: "default",
    },
    {
      accessor: "AREA_CD",
      columnName: "AREA_CD",
      sequence: 14,
      componentType: "default",
    },
    // {
    //   accessor: "name",
    //   columnName: "Joint Name Infor Type",
    //   sequence: 4,
    //   componentType: "default",
    //   width: 200,
    //   minWidth: 150,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "person",
    //   columnName: "Person Name",
    //   sequence: 5,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    //   isVisible: true,
    // },
    // {
    //   accessor: "DESIGNATION",
    //   columnName: "Designation",
    //   sequence: 6,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 150,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "type",
    //   columnName: "MEM Type A/C No.",
    //   sequence: 7,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 220,
    //   minWidth: 100,
    //   maxWidth: 400,
    // },
    // {
    //   accessor: "REF_PERSON_NAME",
    //   columnName: "Reference Account",
    //   sequence: 8,
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 400,
    // },
    // {
    //   accessor: "PHONE",
    //   columnName: "Contact No.",
    //   sequence: 9,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 120,
    //   maxWidth: 250,
    // },
    // {
    //   accessor: "CUSTOMER_ID",
    //   columnName: "Customer Id",
    //   sequence: 10,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
    // {
    //   accessor: "BIRTH_DATE",
    //   columnName: "BIRTH_DATE",
    //   sequence: 11,
    //   alignment: "center",
    //   componentType: "default",
    //   width: 120,
    //   minWidth: 100,
    //   maxWidth: 200,
    // },
  ],
};
