import { GridMetaDataType } from "components/dataTableStatic";
export const TagAccountsGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Tag Account Request",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "60vh",
      max: "75vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: false,
  },
  filters: [
    {
      accessor: "STATUS",
      columnName: "Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "REQ_TYPE",
      columnName: "Request Type",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_CD",
      columnName: "Account Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "OLD_CB_NO",
      columnName: "Old CB Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "NEW_CB_NO",
      columnName: "New CB Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "REQ_DT",
      columnName: "Request Date",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      //dateFormat: "dd/mm/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "STATUS",
      columnName: "Status",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};

export const TagCardsGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Tag Card Request",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "60vh",
      max: "75vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
  },
  filters: [
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "REQ_TYPE",
      columnName: "Request Type",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_CD",
      columnName: "Card Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "OLD_CB_NO",
      columnName: "Old CB Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "NEW_CB_NO",
      columnName: "New CB Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "REQ_DT",
      columnName: "Request Date",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      //dateFormat: "dd/mm/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "STATUS",
      columnName: "Status",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
