import { GridMetaDataType } from "components/dataTableStatic";
import { isValid } from "date-fns";

export const strBranchLevelEntryGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "65vh",
      max: "65vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [
    // {
    //   accessor: "SUSP_DESC",
    //   columnName: "Suspicious Status",
    //   // columnName: "Show Not a Suspicious",
    //   filterComponentType: "valueFilter",
    //   gridProps: {
    //     xs: 12,
    //     md: 12,
    //     sm: 12,
    //   },
    // },
  ],
  columns: [
    {
      accessor: "id",
      columnName: "SrNo",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "ACCT_BRANCH_CD",
      columnName: "BranchCode",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 130,
      maxWidth: 160,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccountType",
      sequence: 2,
      alignment: "right",
      componentType: "default",
      width: 80,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_CD",
      columnName: "AccountNo",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account Name",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 400,
      minWidth: 420,
      maxWidth: 480,
    },
    {
      accessor: "SUSP_DESC",
      columnName: "Suspicious Status",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 200,
      minWidth: 250,
      maxWidth: 300,
    },
    {
      accessor: "REASON_DESC",
      columnName: "Suspicious Reasons",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 250,
      minWidth: 300,
      maxWidth: 350,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      accessor: "GROUND_OF_SUSPICION",
      sequence: 7,
      buttonLabel: "Ground Of Suspicion",
      isVisible: true,
      width: 200,
      minWidth: 250,
      maxWidth: 280,
    },
    {
      accessor: "ACT_FROM_DT",
      columnName: "From Date",
      sequence: 8,
      alignment: "center",
      componentType: "date",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ACT_TO_DT",
      columnName: "To Date",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "TRAN_BAL",
      columnName: "Balance",
      sequence: 10,
      alignment: "right",
      componentType: "currency",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "PAN_NO",
      columnName: "Pan no.",
      sequence: 11,
      alignment: "right",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "REMARKS2",
      columnName: "Investigation Detail",
      sequence: 12,
      alignment: "right",
      componentType: "default",
      width: 300,
      minWidth: 320,
      maxWidth: 380,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 13,
      alignment: "right",
      componentType: "default",
      width: 450,
      minWidth: 460,
      maxWidth: 500,
    },
  ],
};
export const strBranchLevelHistoryGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "55vh",
      max: "55vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [

  ],
  columns: [
    {
      accessor: "id",
      columnName: "SrNo",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 120,
      isAutoSequence: true,
    },

    {
      accessor: "SUSP_DESC",
      columnName: "Suspicious Status",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 200,
      minWidth: 250,
      maxWidth: 300,
    },
    {
      accessor: "REASON_DESC",
      columnName: "Suspicious Reasons",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 300,
      minWidth: 310,
      maxWidth: 350,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 450,
      minWidth: 460,
      maxWidth: 500,
    },
    {
      accessor: "ACT_FROM_DT",
      columnName: "From Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ACT_TO_DT",
      columnName: "To Date",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },


  ],
};
