import { GridMetaDataType } from "components/dataTableStatic";
export const DocumentGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Document",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "SR_CD",
      sequence: 1,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Document",
      accessor: "DESCRIPTION",
      sequence: 2,
      componentType: "default",
      width: 200,
    },
    {
      columnName: "Submitted",
      accessor: "SUBMIT",
      sequence: 3,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Valid Upto",
      accessor: "VALID_UPTO",
      sequence: 4,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Entered From",
      accessor: "Enteredfr",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Document Type",
      accessor: "TEMPLATE_DOC_TYPE",
      sequence: 6,
      componentType: "default",
      width: 200,
    },
    {
      columnName: "Document Amount",
      accessor: "DOC_AMOUNT",
      sequence: 7,
      componentType: "currency",
      width: 160,
    },
  ],
};
