import { GridMetaDataType } from "@acuteinfo/common-base";
export const DocumentGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Document",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    footerNote: "*Double click on records for detailed view",
  },
  filters: [],
  columns: [
    {
      columnName: "Sr No.",
      accessor: "SR_CD",
      sequence: 1,
      componentType: "default",
      alignment: "left",
      width: 60,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      columnName: "Document",
      accessor: "DESCRIPTION",
      sequence: 2,
      componentType: "default",
      width: 200,
    },
    {
      columnName: "Submitted",
      accessor: "SUBMIT",
      sequence: 3,
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 120,
      minWidth: 100,
      maxWidth: 140,
    },
    {
      columnName: "Valid Upto",
      accessor: "VALID_UPTO",
      sequence: 4,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Entered From",
      accessor: "DOC_TYPE",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Document Type",
      accessor: "TEMPLATE_DOC_TYPE",
      sequence: 6,
      componentType: "default",
      width: 200,
    },
    {
      columnName: "Document Amount",
      accessor: "DOC_AMOUNT",
      sequence: 7,
      componentType: "currency",
      alignment: "right",
      width: 160,
    },
  ],
};
