import { GridMetaDataType } from "@acuteinfo/common-base";
export const APYGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "APY",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "type",
      accessor: "SELF_JOINT",
      sequence: 2,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "SubscriberName",
      accessor: "ACCT_NM",
      sequence: 3,
      componentType: "default",
      width: 220,
    },
    {
      columnName: "CustomerId",
      accessor: "CUSTOMER_ID",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 100,
    },

    {
      columnName: "RegistrationNumber",
      accessor: "TRAN_CD",
      alignment: "right",
      sequence: 5,
      componentType: "default",
      width: 125,
    },
    {
      columnName: "RegistrationDate",
      accessor: "TRAN_DT",
      sequence: 6,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 130,
    },
    {
      columnName: "LastPremiumDate",
      accessor: "UPLOAD_DT",
      sequence: 7,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 140,
    },
    {
      columnName: "Nominee",
      accessor: "NOMINEE_NM",
      sequence: 8,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "NomineeRelation",
      accessor: "NOMINEE_RELATION_TYPE",
      sequence: 9,
      componentType: "default",
      width: 165,
    },
    {
      columnName: "InsuranceThrough",
      accessor: "APY_TRAN_CD",
      sequence: 10,
      componentType: "default",
      width: 150,
    },
    {
      columnName: "Active",
      accessor: "ACTIVE",
      sequence: 11,
      componentType: "default",
      width: 100,
    },
  ],
};
