import { GridMetaDataType } from "components/dataTableStatic";
export const ParameterConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Parameter Confirmation",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    //isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "STATUS",
      columnName: "Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "PARA_TYPE",
      columnName: "Type",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "PARA_CD",
      columnName: "Code",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "PARA_NM",
      columnName: "Parameter Description",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 120,
      maxWidth: 300,
    },
    {
      accessor: "PARA_VALUE",
      columnName: "New Parameter Value",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 240,
      minWidth: 180,
      maxWidth: 400,
    },
    {
      accessor: "OLD_VALUE",
      columnName: "Old Parameter Value",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 240,
      minWidth: 180,
      maxWidth: 400,
    },
    {
      accessor: "DATATYPE_CD",
      columnName: "New Datatype",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "OLD_DATATYPE_CD",
      columnName: "Old Datatype",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      //dateFormat: "dd/mm/yyyy",
      width: 160,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
