import { GridMetaDataType } from "components/dataTableStatic";
export const DisbursementGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Disbursement",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Effective Date",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_FROM",
      columnName: "Disbursement Date",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      isVisible: true,
    },
    {
      accessor: "CHEQUE_TO",
      columnName: "Disbursement Amount",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_TOTAL",
      columnName: "Installment Type",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "UNUSED_CHQ",
      columnName: "No. of Installment",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "AMOUNT",
      columnName: "Installment Amount",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "0",
      columnName: "Remarks",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "1",
      columnName: "Next Installment Start Date",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "2",
      columnName: "Int. Date",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "3",
      columnName: "Entered Date",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
