import { GridMetaDataType } from "components/dataTableStatic";
export const MFSGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "MFS Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "OPERATOR_NAME",
      columnName: "Operator Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      isAutoSequence: true,
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "TRN_TYPE",
      columnName: "MFS Service",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "OPERATOR_ID",
      columnName: "Operator ID",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "OPERATOR_NAME",
      columnName: "Operator Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "MAX_DAY_LIMIT",
      columnName: "Maximun Daily Limit",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
    },
    // {
    //   accessor: "MAX_DAY_CNT",
    //   columnName: "Maximun Daily Transaction Count",
    //   sequence: 4,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 200,
    //   minWidth: 150,
    //   maxWidth: 300,
    // },
    // {
    //   accessor: "MAX_MONTH_CNT",
    //   columnName: "Maximum Monthly Transaction Count",
    //   sequence: 5,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 140,
    //   minWidth: 150,
    //   maxWidth: 300,
    // },
    {
      accessor: "TRN_LABEL_EN",
      columnName: "MFS Label (English)",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "TRN_LABEL_BN",
      columnName: "MFS Label (Local)",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirmation Status",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 10,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
    {
      accessor: "TRAN_CD",
      columnName: "Tran Code",
      sequence: 11,
      alignment: "center",
      componentType: "default",
      isVisible: false,
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
  ],
};
