import { GridMetaDataType } from "components/dataTableStatic";
export const gridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Mode Master (EMST/065)",
    rowIdColumn: "MODE_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true, 
    pageSizes: [15, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "MODE_CD",
      columnName: "Mode",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "MODE_NM",
      columnName: "Description",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "MIN_NO_OF_JOINT",
      columnName: "Minimum No. of Joints",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "MAX_NO_OF_JOINT",
      columnName: "Maximum No. of Joints",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "MODE_CD",
      columnName: "Mode",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 500,
    },
    { 
      accessor: "MODE_NM",
      columnName: "Description",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 350,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "MIN_NO_OF_JOINT",
      columnName: "Minimum No. of Joints",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 160,
      maxWidth: 500,
    },
    {
      accessor: "MAX_NO_OF_JOINT",
      columnName: "Maximum No. of Joints",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 500,
    },
  ],
};
