import { GridMetaDataType } from "components/dataTableStatic";

export const InwardClearingRetrievalMetadata = {
  form: {
    name: "InwardClearingForm",
    label: "Parameters",
    resetFieldOnUnmount: false,
    validationRun: "onBlur",
    submitAction: "home",
    render: {
      ordering: "auto",
      renderType: "simple",
      gridConfig: {
        item: {
          xs: 12,
          sm: 4,
          md: 4,
        },
        container: {
          direction: "row",
          spacing: 1,
        },
      },
    },
    componentProps: {
      textField: {
        fullWidth: true,
      },
      select: {
        fullWidth: true,
      },
      datePicker: {
        fullWidth: true,
      },
      numberFormat: {
        fullWidth: true,
      },
      inputMask: {
        fullWidth: true,
      },
      datetimePicker: {
        fullWidth: true,
      },
    },
  },
  fields: [
    {
      render: {
        componentType: "radio",
      },
      name: "A_FLAG",
      label: "",
      RadioGroupProps: { row: true },
      defaultValue: "A",
      options: [
        {
          label: "Only Error",
          value: "E",
        },
        { label: "All", value: "A" },
        { label: "Confirmation Pending", value: "P" },
        { label: "Draft/Banker Cheques", value: "D" },
        { label: "Share Dividend Warrant", value: "S" },
      ],

      GridProps: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 12,
        xl: 12,
      },
    },
    {
      render: {
        componentType: "radio",
      },
      name: "A_RETRIEVE",
      label: "",
      RadioGroupProps: { row: true },
      defaultValue: "A",
      options: [
        {
          label: "Ent.Branch",
          value: "E",
        },
        { label: "A/C Branch", value: "A" },
      ],

      GridProps: {
        xs: 6,
        sm: 6,
        md: 6,
        lg: 6,
        xl: 6,
      },
    },
  ],
};

export const InwardCleaingGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Inward Clearing Process(TRN/650)",
    rowIdColumn: "CHEQUE_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      accessor: "CHEQUE_NO",
      columnName: "Cheque No.",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 110,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_DT",
      columnName: "Cheque Date",
      sequence: 2,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "AMOUNT",
      columnName: "Amount",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "FROM_BANK_CD",
      columnName: "From Bank",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 110,
      maxWidth: 200,
    },
    {
      accessor: "MICR_TRAN_CD",
      columnName: "MICR",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 75,
      minWidth: 80,
      maxWidth: 100,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 350,
      maxWidth: 450,
    },

    {
      columnName: "Cheque/Sign",
      componentType: "buttonRowCell",
      accessor: "SIGN_PATH",
      sequence: 7,
      buttonLabel: "Cheque/Sign",
      isVisible: true,
      width: 100,
      minWidth: 110,
      maxWidth: 200,
    },
    {
      columnName: "Post",
      componentType: "buttonRowCell",
      accessor: "POST_CONF",
      sequence: 8,
      isVisible: true,
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      columnName: "Return",
      componentType: "buttonRowCell",
      accessor: "RETURN",
      sequence: 8,
      buttonLabel: "Return",
      isVisible: true,
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch Code",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 80,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "BRANCH_NM",
      columnName: "Branch Name",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 250,
      minWidth: 180,
      maxWidth: 500,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "Account type",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_CD",
      columnName: "Account Number",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account Name",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "WIDTH_BAL",
      columnName: "Widthdraw.Balance",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
  ],
};
