import { GridMetaDataType } from "components/dataTableStatic";
export const SubsidyGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Subsidy",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Effective Date",
      accessor: "2",
      sequence: 2,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Debit from A/C",
      accessor: "3",
      sequence: 3,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Amount",
      accessor: "4",
      sequence: 4,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Expiry Date",
      accessor: "5",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Remarks",
      accessor: "6",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Entered Date",
      accessor: "7",
      sequence: 7,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Active",
      accessor: "8",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Credit to Party",
      accessor: "9",
      sequence: 9,
      componentType: "default",
      width: 120,
    },
  ],
};
