import { GridMetaDataType } from "@acuteinfo/common-base";
export const SubsidyGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Subsidy",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Effective Date",
      accessor: "EFFECTIVE_DT",
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },

    {
      columnName: "Amount",
      accessor: "AMOUNT",
      sequence: 4,
      componentType: "default",
      width: 120,
      alignment: "right",
    },
    {
      columnName: "Expiry Date",
      accessor: "EXPIRY_DT",
      sequence: 5,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Entered Date",
      accessor: "ENTERED_DATE",
      sequence: 7,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Active",
      accessor: "ACTIVE_FLAG",
      sequence: 8,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Credit to Party",
      accessor: "CR_TO_PARTY",
      sequence: 9,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Debit from A/C",
      accessor: "TRF_ACCT_NM",
      sequence: 10,
      componentType: "default",
      width: 220,
    },
  ],
};
