import { GridMetaDataType } from "components/dataTableStatic";

export const chequeBkConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ChequeBook Confirmation",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "71vh",
      max: "71vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    hiddenFlag: "_hidden",
    searchPlaceholder: "Records of Chequebook Confirmation",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "TRAN_DT",
      columnName: "Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 90,
      minWidth: 70,
      maxWidth: 120,
    },

    {
      accessor: "FULL_ACCT_NO",
      columnName: "Account No.",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account Holder Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 190,
      maxWidth: 290,
    },

    {
      accessor: "CHEQUE_SERIES",
      columnName: "Cheque Series",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 125,
      minWidth: 90,
      maxWidth: 150,
    },

    {
      accessor: "CHEQUE_TOTAL",
      columnName: "No. of Cheque(s)",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 140,
      minWidth: 70,
      maxWidth: 160,
    },

    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Last Entered By",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 103,
      minWidth: 80,
      maxWidth: 150,
    },

    {
      accessor: "SERVICE_TAX",
      columnName: "GST",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 65,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "TRAN_BAL",
      columnName: "Balance",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 110,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "AUTO_CHQBK_FLAG",
      columnName: "Auto Issue Flag",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 129,
      minWidth: 115,
      maxWidth: 200,
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "Verified By",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
