import { GridMetaDataType } from "components/dataTableStatic";
export const CustomerDetailsGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Customer Details",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    hideFooter: false,
    disableGroupBy: true,
    enablePagination: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "42vh",
      max: "50vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    disableGlobalFilter: true,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_CD",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_CD",
      columnName: "Account/Card Number",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "APP_CUSTOMER_ID",
      columnName: "CB Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_TYPE_NAME",
      columnName: "Account Type",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 100,
      maxWidth: 500,
      showTooltip: true,
    },
    {
      accessor: "CUST_NAME",
      columnName: "Customer Name",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 100,
      maxWidth: 500,
      showTooltip: true,
    },
    {
      accessor: "MOBILE_NO",
      columnName: "Mobile Number",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "MAIL_ID",
      columnName: "E-Mail ID",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 100,
      maxWidth: 250,
      showTooltip: true,
    },
    {
      accessor: "TIN",
      columnName: "TIN Number",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "NID",
      columnName: "National ID",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "BIRTH_DATE",
      columnName: "Birth Date",
      sequence: 10,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "GENDER",
      columnName: "Gender",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "MOTHERS_NAME",
      columnName: "Mother Name",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "FATHERS_NAME",
      columnName: "Father Name",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "IDENTIFICATION_NO",
      columnName: "Identification No.",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
