import { GridMetaDataType } from "components/dataTableStatic";
export const ReleaseUserGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Release Block Users",
    rowIdColumn: "CUSTOM_USER_NM",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "48vh",
      max: "48vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
  },
  filters: [
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "sr_no",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CUST_NAME",
      columnName: "Customer Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "BLOCK_DATE",
      columnName: "Block Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy hh:mm:ss",
      width: 150,
      minWidth: 140,
      maxWidth: 200,
    },
    {
      accessor: "BLOCK_REASON",
      columnName: "Block Reason",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
export const ReleaseCardUserGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Release Card PIN Block Users",
    rowIdColumn: "CUSTOM_USER_NM",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "68vh",
      max: "70vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
  },
  filters: [
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "sr_no",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
      isAutoSequence: true,
      isColumnHidingDisabled: true,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      isColumnHidingDisabled: true,
    },
    {
      accessor: "CUST_NAME",
      columnName: "Customer Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
      isColumnHidingDisabled: true,
    },
    {
      accessor: "BLOCK_DATE",
      columnName: "Block Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy hh:mm:ss",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "BLOCK_REASON",
      columnName: "Block Reason",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};

export const BeforeReleaseUsersGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Release Block Users",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "48vh",
      max: "48vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
  },
  filters: [
    {
      accessor: "SR_CD",
      columnName: "Sr. No.",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_CD",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "REQ_DT",
      columnName: "Request Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_NO",
      columnName: "Account Number",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 230,
    },
    {
      accessor: "DISCRIPTION",
      columnName: "Activity Type",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 240,
      maxWidth: 500,
    },
  ],
};

// export const ReleaseUsersGridMetaData = {
//   gridConfig: {
//     dense: false,
//     pageSize: [20, 30, 50],
//     defaultPageSize: "20",
//     gridLabel: "Release Block Users",
//     rowIdColumn: "username",
//     allowColumnReordering: true,
//     allowColumnHiding: true,
//     allowKeyboardNavigation: true,
//     allowGlobalFilter: true,
//     allowFilter: true,
//   },
//   filters: [
//     {
//       accessor: "USER_NAME",
//       columnName: "Login ID",
//       filterComponentType: "valueFilter",
//       gridProps: {
//         xs: 12,
//         md: 12,
//         sm: 12,
//       },
//     },
//   ],
//   columns: [
//     {
//       accessor: "sr_no",
//       columnName: "Sr.No.",
//       sequence: 1,
//       alignment: "left",
//       componentType: "default",
//       width: 80,
//       minWidth: 80,
//       maxWidth: 200,
//     },
//     {
//       accessor: "USER_NAME",
//       columnName: "Login ID",
//       sequence: 2,
//       alignment: "left",
//       componentType: "default",
//       width: 120,
//       minWidth: 100,
//       maxWidth: 200,
//     },
//     {
//       accessor: "CUST_NAME",
//       columnName: "Customer Name",
//       sequence: 3,
//       alignment: "left",
//       componentType: "default",
//       width: 200,
//       minWidth: 100,
//       maxWidth: 400,
//     },
//     {
//       accessor: "BLOCK_DATE",
//       columnName: "Block Date",
//       sequence: 4,
//       alignment: "center",
//       componentType: "date",
//       dateFormat: "dd/MM/yyyy",
//       width: 120,
//       minWidth: 100,
//       maxWidth: 200,
//     },
//     {
//       accessor: "BLOCK_REASON",
//       columnName: "Block Reason",
//       sequence: 5,
//       alignment: "left",
//       componentType: "default",
//       width: 150,
//       minWidth: 100,
//       maxWidth: 200,
//     },
//   ],
// };
