import { GridMetaDataType } from "components/dataTableStatic";
export const StockGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Stock Entry Detail",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Statement Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ASON_DT",
      columnName: "Stock Till Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "STOCK_DESC",
      columnName: "Stock Decription",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 100,
      maxWidth: 290,
      isVisible: true,
    },
    {
      accessor: "MARGIN",
      columnName: "Margin",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 90,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      accessor: "STOCK_VALUE",
      columnName: "Stock Value",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "DRAWING_POWER",
      columnName: "Drawing Power",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "AMOUNT",
      columnName: "Security Decription",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 8,
      alignment: "center",
      componentType: "date",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "RECEIVED_DT",
      columnName: "Recieved Date",
      sequence: 9,
      alignment: "left",
      componentType: "date",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
