import { GridMetaDataType } from "components/dataTableStatic";
export const UserCreationGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Admin Panel User Creation",
    rowIdColumn: "USER_NAME",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
  },
  filters: [
    {
      accessor: "USER_NAME",
      columnName: "User Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "USER_LEVEL",
      columnName: "User Level",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "GROUP_NAME",
      columnName: "User Group Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "USER_NAME",
      columnName: "User ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "User Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "USER_LEVEL",
      columnName: "User Level",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 60,
      maxWidth: 400,
    },
    {
      accessor: "GROUP_NAME",
      columnName: "Group Name",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ALLOW_RELEASE",
      columnName: "Allow Release",
      sequence: 5,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },

    {
      accessor: "CONTACT2",
      columnName: "Mobile No.",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "USER_SUB_TYPE",
      columnName: "User Sub type",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "EMAIL_ID",
      columnName: "Email ID",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },

    {
      accessor: "NOTIF_DESCR",
      columnName: "Notification Template",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },

    {
      accessor: "NOTIF_TEMPL_TRAN_CD",
      columnName: "NOTIFICATION TEMPLATE",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      isVisible: false,
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },
  ],
};
