import { GridMetaDataType } from "components/dataTableStatic";
export const atmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Card Details",
    rowIdColumn: "ACCT_NM",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    disableGlobalFilter: true,
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "29vh",
      max: "29vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SRNO",
      columnName: "SrNo",
      sequence: 1,
      componentType: "default",
      width: 75,
      minWidth: 50,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "REQ_DT",
      columnName: "Request Date",
      sequence: 2,
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      maxWidth: 200,
      minWidth: 150,
    },
    {
      accessor: "STATUS",
      columnName: "Card Status",
      componentType: "default",
      sequence: 2,
      alignment: "center",
      width: 100,
      minWidth: 200,
      maxWidth: 400,
    },

    {
      accessor: "ISSUE_TO",
      columnName: "Issue To",
      sequence: 4,
      componentType: "default",
      width: 120,
      alignment: "center",
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "Customer Id",
      sequence: 5,
      componentType: "default",
      width: 120,
      alignment: "center",
    },
    {
      accessor: "ACCT_NM",
      columnName: "Name",
      sequence: 6,
      componentType: "default",
      width: 90,
      maxWidth: 100,
      minWidth: 50,
      alignment: "left",
    },
    {
      accessor: "ISSUE_DT",
      columnName: "Issue/Reject Date",
      sequence: 7,
      componentType: "date",
      width: 120,
      alignment: "center",
    },

    {
      accessor: "CITIZEN_ID",
      columnName: "Citizen Id",
      sequence: 8,
      componentType: "default",
      width: 120,
      alignment: "center",
    },
    {
      accessor: "M_CARD_NO",
      columnName: "Card No",
      sequence: 9,
      componentType: "default",
      width: 120,
      alignment: "center",
    },
    {
      accessor: "CARD_TYPE",
      columnName: "Card Type",
      sequence: 10,
      componentType: "default",
      alignment: "center",
      width: 120,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 11,
      componentType: "default",
      alignment: "center",
      width: 120,
    },
    {
      accessor: "DEACTIVE_DT",
      columnName: "De-active(Lost/Destroy) Date",
      sequence: 12,
      componentType: "date",
      alignment: "center",
      // dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      accessor: "ALLOW_DELETE",
      columnName: "Action",
      buttonLabel: "Delete",
      sequence: 4,
      alignment: "center",
      componentType: "buttonRowCell",

      width: 90,
      minWidth: 60,
      maxWidth: 130,
    },
  ],
};
