import { GridMetaDataType } from "components/dataTableStatic";
export const JointDetailGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Joint Details",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr.",
      accessor: "SR_CD",
      sequence: 1,
      componentType: "default",
      width: 60,
    },
    {
      columnName: "Joint Name Info Type",
      accessor: "J_TYPE",
      sequence: 2,
      componentType: "default",
      width: 150,
    },
    {
      columnName: "Person Name",
      accessor: "REF_PERSON_NAME",
      sequence: 3,
      componentType: "default",
      width: 60,
    },
    {
      columnName: "Designation",
      accessor: "DESIGNATION",
      sequence: 4,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Mem Type A/C No.",
      accessor: "MEM_ACCT_CD",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Reference A/C",
      accessor: "REF_ACCT_CD",
      sequence: 6,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Contact No.",
      accessor: "phone1",
      sequence: 7,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Customer ID",
      accessor: "CUSTOMER_ID",
      sequence: 8,
      componentType: "default",
      width: 100,
    },
    {
      accessor: "ACCT_CD",
      columnName: "ACCT No",
      sequence: 9,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "A/C Type",
      sequence: 10,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch No",
      sequence: 11,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "COMP_CD",
      columnName: "COMP_CD",
      sequence: 12,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "ADD1",
      columnName: "Address",
      sequence: 13,
      componentType: "default",
      width: 200,
    },

    {
      accessor: "PIN_CODE",
      columnName: "Pin Code",
      sequence: 14,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "BIRTH_DATE",
      columnName: "BIRTH_DATE",
      sequence: 15,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },

    {
      accessor: "AREA_CD",
      columnName: "AREA_CD",
      sequence: 16,
      componentType: "default",
      width: 120,
    },
  ],
};
