import { GridMetaDataType } from "@acuteinfo/common-base";
export const JointDetailGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Joint Details",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr.",
      accessor: "SR_CD",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Type",
      accessor: "JOINT_DISC",
      sequence: 2,
      componentType: "default",
      width: 100,
    },

    {
      columnName: "Person Name",
      accessor: "REF_PERSON_NAME",
      sequence: 3,
      componentType: "default",
      width: 250,
    },
    {
      columnName: "Designation",
      accessor: "DESIGNATION",
      sequence: 4,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Mem. Type A/C No.",
      accessor: "MEM_ACCT_CD",
      sequence: 5,
      componentType: "default",
      width: 150,
    },
    {
      columnName: "Reference Account",
      accessor: "REF_ACCT_CD",
      sequence: 6,
      componentType: "default",
      width: 150,
    },
    {
      columnName: "Contact No.",
      accessor: "phone1",
      sequence: 7,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Customer ID",
      accessor: "CUSTOMER_ID",
      sequence: 8,
      componentType: "default",
      width: 100,
    },
  ],
};
