import { GridMetaDataType } from "components/dataTableStatic";
export const ParameterConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "User Block Configuration Confirmation",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    //isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "STATUS",
      columnName: "Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "CONFIG_TYPE",
      columnName: "Config Type",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "CONFIG_DESC",
      columnName: "Description",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "FAIL_ATTEMPT",
      columnName: "Fail Attempt",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      placeholder: "",
      width: 100,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "OLD_FAIL_ATTEMPT",
      columnName: "Old Fail Attempt",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      placeholder: "",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "BLOCK_MINUTE",
      columnName: "Minutes Of Block",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      placeholder: "",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "OLD_BLOCK_MINUTE",
      columnName: "Old Minutes Of Block",
      sequence: 7,
      alignment: "right",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 9,
      alignment: "center",
      componentType: "default",
      //dateFormat: "dd/mm/yyyy",
      width: 160,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
