import { GridMetaDataType } from "components/dataTableStatic";
export const PrimaryIDChangeGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Primary Identifier Change Confirmation",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "60vh",
      max: "75vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    //isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "STATUS",
      columnName: "Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "USER_NAME",
      columnName: "User Name",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "OLD_PRIMARY_SOURCE",
      columnName: "Old Primary Source",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 170,
    },
    {
      accessor: "PRIMARY_APP_SOURCE",
      columnName: "New Primary Source",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 170,
    },
    {
      accessor: "OLD_PRIMARY_CBNUMBER",
      columnName: "Old CB Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "PRIMARY_CBNUMBER",
      columnName: "New CB Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "OLD_REG_CARD_ACCT_NO",
      columnName: "Old Card/Account Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 190,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "REG_CARD_ACCT_NO",
      columnName: "New Card/Account Number",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 190,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      //dateFormat: "dd/mm/yyyy",
      width: 160,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
