import { GridMetaDataType } from "components/dataTableStatic";

export const LoanScheduleGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    // enablePagination: true,
    // pageSizes: [20, 40, 60],
    defaultPageSize: 20,
    containerHeight: {
      min: "28vh",
      max: "28vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
    hideFooter: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 40,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "DISBURSEMENT_DT",
      columnName: "Disbursement Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 170,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "DISBURSEMENT_AMT",
      columnName: "Disbursement Amount",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 170,
      minWidth: 120,
      maxWidth: 250,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "INST_TYPE_DIS",
      columnName: "Installment Type",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INST_NO",
      columnName: "No. of Installment",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INS_START_DT",
      columnName: "Next Installment Start Date",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 200,
      minWidth: 170,
      maxWidth: 250,
    },
    {
      accessor: "INST_RS",
      columnName: "Disburse Installment Amount",
      sequence: 7,
      alignment: "right",
      componentType: "default",
      width: 200,
      minWidth: 170,
      maxWidth: 250,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 220,
      maxWidth: 700,
      showTooltip: true,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      accessor: "REVISE_FLAG",
      sequence: 20,
      buttonLabel: "Revise",
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.ACTIVE === "Y") {
          return false;
        }
        return true;
      },
      width: 100,
      minWidth: 80,
      maxWidth: 110,
    },
    {
      accessor: "SR_CD",
      columnName: "Sr cd",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
      isVisible: false,
    },
  ],
};

export const LoanScheduleDetailsGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    disableGroupBy: true,
    // enablePagination: true,
    // pageSizes: [20, 40, 60],
    defaultPageSize: 20,
    containerHeight: {
      // min: "25vh",
      // max: "25vh",
      min: "45vh",
      max: "45vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },
  columns: [
    {
      accessor: "SR_CD",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 60,
      maxWidth: 150,
    },
    {
      accessor: "INS_START_DT",
      columnName: "Installment Start Date",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 200,
      minWidth: 170,
      maxWidth: 250,
    },
    {
      accessor: "BEGIN_BAL",
      columnName: "Beginning Balance",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 180,
      minWidth: 160,
      maxWidth: 200,
    },
    {
      accessor: "INT_RATE",
      columnName: "Interest Rate(%)",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 200,
    },
    {
      accessor: "INST_RS",
      columnName: "Installment Amount",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 180,
      minWidth: 160,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "PRIN_DEMAND_AMT",
      columnName: "Principal Demand",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 180,
      minWidth: 160,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "INT_DEMAND_AMT",
      columnName: "Interest Demand",
      sequence: 7,
      alignment: "right",
      componentType: "default",
      width: 180,
      minWidth: 160,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "END_BAL",
      columnName: "Ending Balance",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      accessor: "EDIT_BTN",
      sequence: 20,
      buttonLabel: "Edit",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.EDIT_FLAG === "Y") {
          return false;
        }
        return true;
      },
    },
  ],
};
