export const CardCategoryMasterGridMetaData = {
  gridConfig: {
    dense: true,
    gridLabel: "Card Category Master",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "68vh", max: "68vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
  },
  columns: [
    {
      columnName: "ID",
      componentType: "default",
      accessor: "TRAN_CD",
      sequence: 1,
      alignment: "left",
      width: 70,
      maxWidth: 100,
      minWidth: 50,
      isAutoSequence: true,
    },
    {
      columnName: "Card Prefix",
      componentType: "default",
      accessor: "CARD_PERFIX",
      sequence: 3,
      alignment: "left",
      width: 120,
      maxWidth: 200,
      minWidth: 100,
    },
    {
      columnName: "Card Category Code",
      componentType: "default",
      accessor: "CATEGORY_CD",
      sequence: 3,
      alignment: "left",
      width: 150,
      maxWidth: 200,
      minWidth: 120,
    },
    {
      columnName: "Card Description",
      componentType: "default",
      accessor: "DESCRIPTION",
      sequence: 3,
      alignment: "left",
      width: 150,
      maxWidth: 200,
      minWidth: 120,
    },
  ],
};
export const CardCategoryMasterConfirmationGridMetaData = {
  gridConfig: {
    dense: true,
    gridLabel: "Card Category Master Confirmation",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "68vh", max: "68vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
  },
  columns: [
    {
      columnName: "ID",
      componentType: "default",
      accessor: "TRAN_CD",
      sequence: 1,
      alignment: "left",
      width: 70,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Card Prefix",
      componentType: "default",
      accessor: "CARD_PERFIX",
      sequence: 3,
      alignment: "left",
      width: 120,
      maxWidth: 200,
      minWidth: 100,
    },
    {
      columnName: "Card Category Code",
      componentType: "default",
      accessor: "CATEGORY_CD",
      sequence: 3,
      alignment: "left",
      width: 150,
      maxWidth: 200,
      minWidth: 120,
    },
    {
      columnName: "Card Description",
      componentType: "default",
      accessor: "DESCRIPTION",
      sequence: 3,
      alignment: "left",
      width: 150,
      maxWidth: 200,
      minWidth: 120,
    },
  ],
};
