import { GridMetaDataType } from "components/dataTableStatic";

export const AppVersionMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Application Version Master",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "DEVICE_OS",
      columnName: "Device O.S.",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "VERSION_NO",
      columnName: "Version",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DISP_IS_POPUP",
      columnName: "Popup Message",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      placeholder: "",
      width: 125,
      minWidth: 80,
      maxWidth: 150,
      color: (value, row) => {
        if (row?.original?.IS_LATEST_VERSION === "Y") {
          return "var(--theme-color1)";
        }
      },
    },
    {
      accessor: "DISP_IS_FORCE_UPDATE",
      columnName: "Force Update",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 110,
      minWidth: 80,
      maxWidth: 150,
    },
    // {
    //   accessor: "CONFIRM_STATUS",
    //   columnName: "Confirmed Status",
    //   sequence: 5,
    //   alignment: "left",
    //   componentType: "default",
    //   placeholder: "",
    //   width: 150,
    //   minWidth: 120,
    //   maxWidth: 200,
    //   isDisabledOnBlurEvent: true,
    // },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 110,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 7,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 110,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 9,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
  ],
};
