import { GridMetaDataType } from "@acuteinfo/common-base";
export const IntPaidDtlGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SRCD",
    defaultColumnConfig: {
      width: 250,
      maxWidth: 300,
      minWidth: 200,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
      isAutoSequence: true,
      isDisplayTotal: true,
      footerIsMultivalue: true,
      footerLabel: "Total :",
      setFooterValue(total, rows) {
        return "";
      },
    },
    {
      accessor: "ACCT_CD",
      columnName: "A/C No.",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "FD_NO",
      columnName: "FD Number",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 150,
    },
    {
      accessor: "PAID_STATUS",
      columnName: "Status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Tran. Date",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "FROM_DT",
      columnName: "From Date",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "TO_DT",
      columnName: "To Date",
      sequence: 7,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "PROV_INT_AMT",
      columnName: "Prov. Int. Amt.",
      sequence: 8,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 140,
      maxWidth: 200,
      isDisplayTotal: true,
      footerLabel: " ",
    },
    {
      accessor: "PAID_INT_AMT",
      columnName: "Paid Int. Amt.",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 140,
      maxWidth: 200,
      isDisplayTotal: true,
      footerLabel: " ",
    },
    {
      accessor: "TDS_INT_AMT",
      columnName: "TDS Int. Amt.",
      sequence: 10,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 140,
      maxWidth: 200,
      isDisplayTotal: true,
      footerLabel: " ",
    },
    {
      accessor: "CR_AC_NO",
      columnName: "Cr. A/c No.",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 120,
      maxWidth: 160,
    },
  ],
};
