import { GridMetaDataType } from "components/dataTableStatic";
export const UserGroupGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Admin Panel User Group",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
  },
  filters: [
    {
      accessor: "GROUP_NAME",
      columnName: "User Group",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "RECENT_DOC_NO",
      columnName: "No. of Screens to display under Recent Option",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "PWD_DAYS",
      columnName: "Login Password Force Expiry Days",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "GROUP_NAME",
      columnName: "User Group",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 200,
      maxWidth: 600,
    },

    {
      accessor: "RECENT_DOC_NO",
      columnName: "No. of Screens under Recent Option",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 350,
    },
    {
      accessor: "PWD_DAYS",
      columnName: "Login Password Force Expiry Days",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 350,
    },
  ],
};
