import { GridMetaDataType } from "components/dataTableStatic";
export const PMBYGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "PMBY",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "Sr",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Type",
      accessor: "ACCT_TYPE",
      sequence: 2,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Applicant Name",
      accessor: "APPLICANT_NM",
      sequence: 3,
      componentType: "default",
      width: 200,
    },
    {
      columnName: "Customer ID",
      accessor: "CUSTOMER_ID",
      sequence: 4,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Registration",
      accessor: "111",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Last Premium",
      accessor: "PREMIUM_AMT",
      sequence: 6,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Premium Nominee",
      accessor: "NOMINEE_NM",
      sequence: 7,
      componentType: "default",
      width: 100,
    },
  ],
};
