export const checklistDetailsGridMetaData = {
  gridConfig: {
    dense: true,
    gridLabel: "Service Charge Details",
    rowIdColumn: "serialNo",
    defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "40vh", max: "50vh" },
  },
  columns: [
    {
      accessor: "serialNo",
      columnName: "Serial No",
      componentType: "default",
      sequence: 1,
      alignment: "left",
      width: 100,
      maxWidth: 150,
      minWidth: 70,
    },
    {
      accessor: "minAmount",
      columnName: "Minimum Amount",
      componentType: "currency",
      sequence: 2,
      alignment: "right",
      width: 150,
      maxWidth: 250,
      minWidth: 130,
      showTooltip: true,
    },
    {
      accessor: "maxAmount",
      columnName: "Maximum Amount",
      componentType: "currency",
      alignment: "right",
      sequence: 2,
      width: 150,
      maxWidth: 250,
      minWidth: 130,
    },
    {
      accessor: "fromLimitAmount",
      columnName: "From Amount",
      componentType: "currency",
      sequence: 3,
      alignment: "right",
      width: 150,
      maxWidth: 250,
      minWidth: 130,
    },
    {
      accessor: "toLimitAmount",
      columnName: "To Amount",
      componentType: "currency",
      sequence: 4,
      alignment: "right",
      width: 150,
      maxWidth: 250,
      minWidth: 130,
    },
    {
      accessor: "chargeAmount",
      columnName: "Charge Amount",
      componentType: "currency",
      sequence: 6,
      alignment: "right",
      width: 150,
      maxWidth: 250,
      minWidth: 130,
    },

    {
      accessor: "chargePercentage",
      columnName: "Charge Percent",
      componentType: "default",
      sequence: 6,
      alignment: "right",
      width: 150,
      maxWidth: 250,
      minWidth: 130,
    },

    {
      accessor: "compareOrAdd",
      columnName: "Compute",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 200,
      maxWidth: 250,
      minWidth: 170,
    },
  ],
};
